### ISSUE TITLE
Unable to swipe left to view settings - MacBook Pro 2018

### ISSUE THREAD

**Issue by cybercussion** [alin23/Lunar#10]
It does pickup the 2 LG Ultrafine 22" monitors, but doesn't seem to allow me to get to the view settings. 

 LG's own display management app only works with 1 monitor plugged in at a time, and these monitors seem to have to have a defect where  the Mac puts the displays to sleep there is a 50/50 chance the monitors don't come back on.  This forces me to manually unplug the USB-C cables and plug them back in.  At least Lunar tries to set the brightness to something respectable vs the stock behavior of 100% brightness.  I don't even think the light sensor they shipped with these monitors works.

**Comment by alin23** [comment]
Yes, I'm aware of the swipe problem. It's actually fixed here on Github, but I wanted to add one more (very requested) feature before releasing a new version. I've been busy with another project these days but I'll try to release the new version these days.

Also, Lunar has some problems coping with multiple monitors of the exact same type. This happens because it constructs a unique ID for each monitor based on the EDID data (things like serial number, hw version etc) extracted from them. But a lot of the time, that data cannot be extracted or is simply not existent so the IDs end up being the same. 

I'm still looking for a solution to this, I'm just letting you know that you might run into this even with the new version.

**Comment by cybercussion** [comment]
Awesome, I'll keep an eye out.  Thanks much.

**Comment by alin23** [comment]
@cybercussion should be fixed now in v2.2.0. Let me know if it works for you ^_^

**Comment by cybercussion** [comment]
Good to go, thanks!
