### ISSUE TITLE
Lunar Diagnostics Report [E30B68473B5779B0DB828CB578DA1C76ED608E31FBDF609A19DF11FB686424F7] [3.2.2]

### ISSUE THREAD

**Issue by Rastafabisch** [alin23/Lunar#103]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
   **No**

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
   **MacBook Pro 15" 2017**

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
   **Dual DisplayPort (5k)**

- Using an USB Docking Station or Hub:
   **eGPU RX Vega 56, but won't work with internal dGPU either** 

- Lunar mode used (check it in the top-right corner of the Lunar interface)
  **Sync, but basically any**

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
   **No :( - executes but does not do anything**

# Issue description:
no reaction of the display whatsoever (not even any flickering…)
**What does work, however is controlling the displays brightness while running the monitor in 4K, single DisplayPort mode.**

**Comment by alin23** [comment]
Hi @Rastafabisch ! 

Unfortunately this is a connection problem. If ddcctl doesn't do anything for you then DDC messages aren't passed correctly to your monitor and there's nothing we can do in software to alleviate this.

The problem seems to be Dual DP which uses pins that are less often used (like the DDC pin) for extra data bandwidth: 

>  DP connectors include pins for the display data channel (DDC), but DP supports DDC within its optional Dual-Mode DP (DP++) feature in DVI/HDMI mode only.

[DDC Wikipedia](https://en.wikipedia.org/wiki/Display_Data_Channel)
