### ISSUE TITLE
Lunar Diagnostics Report [63F95418D6A6D57FDBE7336A018FBCDE899537833441CED971DCCC3C1786FCC1] [3.2.3]

### ISSUE THREAD

**Issue by aguscha333** [alin23/Lunar#124]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    no

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Pro 2019 13"

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI-to-USB-C

- Using an USB Docking Station or Hub:
    no, direct cable from usb-c to hdmi

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync and manual didn't work, didn't even try location because it does not serve me.

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
The first time I installed the program it worked great. After I restarted the laptop at some point, it stopped working. It didn't open at login although that setting is marked to yes and when I opened it manually none of the settings worked. It was not on the questions above but I am using a Samsung monitor, just in case it's helpful.

**Comment by alin23** [comment]
Hi @aguscha333 ! 

Thanks for the detailed report! 

So Lunar was able to change your monitor's brightness before but after a restart it can't do that anymore? Are the cable and laptop/monitor ports used the same as when Lunar was working?

Unfortunately I lost the diagnostics log because the cheap server I use for this ran out of disk space. Could you please run diagnostics again, but without opening another issue this time?

Usually the monitor model doesn't count, all the monitors since 2002 should have DDC implemented. So unless something happened to your cable or your GPU, everything should still work.

The launch at login option was an issue for some time but after I moved to using the LaunchAtLogin framework a few versions ago, it seems to work reliably and people have also reported that this was fixed for them too. I have no idea what could be wrong in Lunar's code in this case.

**Comment by aguscha333** [comment]
Thanks for the quick response! The cable is the same, I've tried on all the usb-c ports my MacBook has and none of them work after that restart that broke it all.

I ran a diagnostics again but didn't create a new issue as you asked. Let me know if you find something or if there is anything else I can do to help you find what is going on.

**Comment by aguscha333** [comment]
Another thing that happens depending on the port I have the cable connected to is that some times when I press the brightness up or down buttons on my magic keyboard the external monitor screen flashes to green and then immediately goes back to normal. Don't know if it has anything to do with lunar but thought it would be worth mentioning

**Comment by alin23** [comment]
Huh, that sounds like a problem with the monitor. Lunar listens for brightness keys when the cursor is on an external monitor and sends a brightness DDC message to that specific monitor. Try to check if that green flash only happens when the cursor is on the external monitor.

I'm taking a look through the logs right now.

**Comment by alin23** [comment]
The logs show no issue with Lunar or the Macbook, the DDC messages seem to get sent but there's no way to see what the monitor does with them. I checked the error reporting tool I use and there's nothing coming from your user id.

So I think it is safe to say that Lunar is not the issue here and most likely it is the cable or the monitor. 

Just yesterday one of my coworkers told me that one of his Thunderbolt 3 to HDMI cables is failing and heating up a lot. The cable in question was this: [Thunderbolt to HDMI cable](https://www.amazon.com/CHOETECH-Thunderbolt-Compatible-MacBook-Samsung/dp/B07L8RW3ZS/ref=sr_1_4?dchild=1&keywords=choetech%2Busb%2Bc%2Bhdmi%2Bcable&qid=1591902143&sr=8-4&th=1)

This type of cable has a signal converter microcontroller inside the big HDMI connector and that  is prone to failing on really high resolutions as that requires a lot of electrical pulses going through the wires. So all I can say for now is, check another cable if you have the possibility.

I'll close the issue as I can't do much on Lunar side.

**Comment by aguscha333** [comment]
I have the same brand of cable different model 😞. So probably that is the problem and won't be able to get it to work. Thanks for taking the time to try and see what was wrong 🙂

**Comment by aguscha333** [comment]
Hi, I just tried on my other MBP (2016 15") with the same cable and it works fine so I don't know if the issue was the cable at last. It is not a pressing issue for me to get this fixed but I thought you might appreciate that new info.

**Comment by alin23** [comment]
Thanks for the info! Most likely it was always an issue with the monitor. Since then I've had multiple reports of monitors that even though have DDC enabled, they only allow DDC writes in Firmware Debug Mode or disable it completely, hence the green flash which I have also seen happening on some of my TV monitors.
