### ISSUE TITLE
Lunar Diagnostics Report [4F04B8E57DABB1F44B4FE975ADE8CA2BCFF99DB0873EC82DF93A515780C3143C] [3.2.3]

### ISSUE THREAD

**Issue by IMD-Y3** [alin23/Lunar#128]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
   No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Pro 15" 2015 (dedicated AMD Gpu)
    LG UltraFine 21.5" 4K (first edition, so 4096x2304 native res: 22MD4KA-B)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    Mini DisplayPort-to-DisplayPort Cable > DP Switch > TB3 PCie Card (TB3 + DP) > CalDigit TB3+ > USB-C on LG UltraFine 4K 

- Using an USB Docking Station or Hub:
    Yes, Caldigit TB3 Plus

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
   Will have to look into it. 

# Issue description:
– I have a slightly bizarre hardware configuration to get the monitor working on older Retina MBP and PC at the same time. Lunar was working fine before (Hotkeys & Sync both worked) when going directly from the TB3 expansion card with TB3 (20gbps) cable to the LG 4K. 
– Then I introduced a CalDigit TB3 dock which broke Lunar :(
– Brightness doesn't adjust at all, and sometimes the app crashes when changing modes. 
– Maybe something with the EDID? I see the monitor is listed in MacOS as "LG UltraFine" via the CalDigit dock. Going directly from the TB3 expansion card device was "LG UltraFine 4k (22")"
– I will try with shorter (0.8m) Passive Thunderbolt 3 cables.
– The display does currently run at full native resolution Cinema 4K @ 60HZ from both inputs (MBP & PC Gtx) even though DP 1.2 only on MBP!

---
Full Setup is like this: 
1) MPB TB2 port: mDP to DP Cable -> DP Active Switch
2) Windows PC GTX 1080: DP to DP Cable -> DP Active Switch
3) DP Active Switch: DP to mDP Cable -> Asus Thunderbolt 3 PCie Expansion Card (mDP input)
4) PCie TB3 port -> CalDigit 2-meter Thunderbolt 3 ACTIVE Cable -> CalDigit TB3+ Hub
5) CalDigit USB-C gen2 / TB3 port -> TB3 Cable (PASSIVE 20gbps) -> LG UltraFine 4K USB-C input  

[Asus Ext3 PCie card is inside PC & splices a DP signal into TB3 port]
[I use a DP Switch to toggle between MBP & PC Gtx 1080 DisplayPort signals before they reach the Asus Ext3 TB3 expansion card]
[Cables and switch all rated for 4K @ 60Hz, no mention of UHD vs Cinema 4K res though?]
[Display does runs at native res Cinema 4K (4096 x 2304) at 60Hz from both Mac & Win DP sources.]

Hope this helps... someone? Dunno who else would have this convoluted setup :)
I'll try some other cables, or go back to running the display directly without the CalDigit... 
Or finally buy a TB3 MBP.... 

Thanks for making such a great tool!
I use something similar on the PC which does work through the CalDigit atm, but quite unpredictable.... Lunar is so polished!!

**Comment by alin23** [comment]
Hey thanks for the detailed report! Yes, docks with more than one video connection are notorious for breaking DDC. I'm afraid to ask what kind of hacks went into that CalDigit to cram 15 ports into a single cable connection.

All I can say is, try all the possible connectors on that caldigit, maybe just one of them supports DDC writes and you have to find which one. Or maybe it doesn't support that at all because of all the bandwidth it needs so you might have to skip it entirely.

It's weird that you have an UltraFine but you don't have a TB3 Macbook. 😅 
What I like the most about this setup is that a single USB-C cable from the monitor to the Macbook handles high-res video, charging, and gives me USB-A connectors on the back of the monitor. I never needed a hub because of this monitor.

**Comment by IMD-Y3** [comment]
Thanks for the speedy reply! I will try a range of cables. 

I did use the monitor as a hub before (Lunar was a great addition!) Unfortunately Apple/LG also had to jump through some tricks to get that single cable magic, so USB hub on the display is limited to 2.0 speeds only. Not great for workflow with large media files sadly 🥶

At least with this hack I have full retina display on Windows also 🤩 and all these cables shoved behind the workstation & only the mDP into MBP. 

Dunno why it’s so hard to find a retina level ‘ultrafine’ monitor with multiple source inputs? No one else is selling this type of panel as far as I know.

Thanks again!

**Comment by alin23** [comment]
Yes, smaller 4k monitors are hard to find. I'm using a 4k 27" LG which has TB3, DP1.2, two HDMI ports, and two USB3 SuperSpeed ports. I never missed anything with it. 4k 27 isn't really Retina but being so far from my eyes makes it look as good as the built-in display of the Macbook.

I'm going to close this issue as there isn't much I can do in Lunar's code to fix it, but feel free to post whatever setup you found that works. I always need to learn what works and what not, so that I can help other users. 

I hope to come up with a better UI for aiding the users in diagnosing this kind of issues themselves in the next Lunar version. I already have a huge backlog for Lunar.. my day job leaves me with no time for Lunar these days.
