### ISSUE TITLE
Lunar Diagnostics Report [0D513EAEECFE86D1F23A3181EA496CAD025AB2000F4F5868831B4E3CD9C3CD1F] [3.2.3]

### ISSUE THREAD

**Issue by JEEZYSAM** [alin23/Lunar#129]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
Yes
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
Hackintosh 19,1
- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
Hackintosh Thunderbolt USB-C
- Using an USB Docking Station or Hub:
No
- Lunar mode used (check it in the top-right corner of the Lunar interface)
Manual
- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
I can't control with native apple keyboard brightness control anymore.

**Comment by alin23** [comment]
Make sure you have this option enabled:
<img width="871" alt="image" src="https://user-images.githubusercontent.com/3819725/85179038-939c1e80-b288-11ea-9c6c-16db4520eb18.png">

Also make sure you also try pressing the brightness key while holding fn key in case you have the function keys by default instead of the media keys.
<img width="552" alt="image" src="https://user-images.githubusercontent.com/3819725/85179149-e1188b80-b288-11ea-9d77-b9529171414e.png">

There was no change in the code for the media keys listener so it's possible that something changed in your setup. Maybe you have another app that overrides the brightness keys.
Also to keep in mind, if you have multiple monitors, Lunar only changes brightness for the monitor where the cursor is placed at that moment.

**Comment by alin23** [comment]
Try removing and readding Lunar in the Input Monitoring section of the Security and Privacy preferences.

Here is another user that solved it in this way:
https://github.com/alin23/Lunar/issues/132#issuecomment-650153635
