### ISSUE TITLE
Feature Requests + Found Bugs

### ISSUE THREAD

**Issue by dougc84** [alin23/Lunar#13]
Just stumbled on this app a couple days ago. I've been using `ddcctl` + Automator services + manually assigned hotkeys to adjust my monitor's values.  My monitor's control button is broken and barely works, and my monitor doesn't support LG's software, so it's the only way I can quickly and reliably adjust settings.  I love the design of this app (it's really pretty!) and functionality that works excellently and is downright solid.

That said, there are a few things I would love to see in this app and a few bugs I've found that I wanted to report.  I'm a Ruby dev, not a ObjC/Swift dev, otherwise I'd happily submit a pull request, but it's just not something I can dive into easily.

1. You have hotkeys for 0%, 25%, etc.  The problem I have is, with my monitor, brightness looks great at 100%, but contrast over 70-75% is washed out and illegible.  I would love to see these 5 custom hotkeys be either reworked to allow variable brightness and contrast levels (so you could set them to whatever), or be able to specify maximum brightness and contrast values that those percentages are based off of (e.g. the 75% level with a max brightness of 100% and max contrast of 70% would set the brightness to 75% and the contrast to 52.5%).
2. On that same note, a maximum (or minimum) brightness or contrast in manual mode would be a really nice addition.  This could tie into the previous point very nicely.
3. Hotkeys are a little buggy.  I reassigned control+F1, didn't like it, and wanted to assign it back.  I couldn't.  That said, I use the media keys, so F1 is actually FN+F1 on my keyboard.
4. Using the menubar icon > Preferences, I'm taken to the main page.  I didn't understand that you had to swipe to go left and right through different pages.  That action should really take you to the correct view.  Also, I jump back and forth between using a standard mouse (non-Apple) and a trackpad, so what's the fallback on navigation when you don't have a left/right scroll/swipe option?
5. Adaptive mode.  I generally work nights, so having noon as my "brightness max" just doesn't work at all.  The controls are nice but I'd love a simpler, more descriptive way of adjusting this - maybe something along the lines of Apple's Night Shift, where you simply select a time to dim and a time to go brighter, perhaps with a transition time?  Maybe you could keep the manual mode, add a "midday time offset" option to the adaptive mode, and a "scheduled" third option that would function like Night Shift.

All that said, thanks for this cool app.  I'm definitely keeping my eye on it!

**Comment by alin23** [comment]
Hi there! 

1. The thing is that's how hotkeys worked a couple of days ago, but other users didn't like that. I'll see how I can make this configurable again. 
2. Yes, separate min/max for manual is a good idea. I'll work on this next time I have some free time.
3. This works for me, I'm not sure what could be the problem:
![hotkey-change](https://media.giphy.com/media/6u2WWJYT3FmGyzyGMD/giphy.gif)
4. The pages can be navigated using arrow keys. You should have seen some red-pink text on the main page of Lunar when you launched it for the first time that would guide you through this. I guess I screwed this up while working on other stuff.
![image](https://user-images.githubusercontent.com/3819725/54371859-d5501980-4682-11e9-8fc2-e67439f617d8.png)
The thing is, all the pages contain preferences in a way or another. I usually want to adjust min/max when I open Lunar because the other settings are more like "fiddle with them until you get it right and forget about them".
5. Location mode is for people that work in rooms with lots of natural light. I used that a lot when I had my office surrounded by 3 glass walls and I implemented it based on my use case. If you have a Mac with a light sensor, it's always better to use Sync mode anyway. What you're describing would be a totally different mode.

I've had a few users email me about different ideas on different adaptive implementations. I can't really implement them all as it would increase the app complexity and new users would have no idea what to choose. 

For your case, I could add a noon offset setting, or if you could elaborate on that scheduled mode, I'll see if I can make it fit somehow.

**Comment by alin23** [comment]
@dougc84 please check v2.3.0 and let me know what else do you think it's missing. I haven't implemented the noon offset thing because I didn't know if you'd still find it useful (and kinda ran out of free time).

The update doesn't address all your concerns yet, so please don't hesitate to go into detail of what feature/change would make Lunar perfect for your use case. I'll try to find a way to meet them.

**Comment by dougc84** [comment]
@alin23 Hey!  Thanks for the heads up.  I could have sworn I responded via email to your last post but I guess I either didn't or GitHub didn't like it.

I'll give the new version a look through tonight.  You rock!

**Comment by dougc84** [comment]
@alin23 Sorry for the delays in getting back.  Since my schedule is constantly veering, I decided against using the adaptive mode since my schedule is just always bizarre, but I really like some of the things you've done!  Manual mode is all I really need, especially with the brightness/contrast caps.

However, a couple things:

When 2.3.3 came out, the auto update failed.  I got this:

![Screen Shot 2019-04-02 at 2 07 15 AM](https://user-images.githubusercontent.com/744509/55379959-b65bdf00-54ec-11e9-83b7-f1c0b457bf8e.png)

Not a big issue - just re-downloaded the DMG and manually installed, but just thought you might want to know.  Also, strangely, the DMG required the control+click > open workaround for non-App Store/unverified apps, but the Lunar app itself didn't.  I dunno if that's just macOS's app history picking it up as the same app, but detecting the DMG as new.

Lastly, the keyboard controls are working nicely.  Using my key commands (command+control+0-4 in my case) respects the new caps very nicely.  However, if I use the key commands (command+option+control+(shift for contrast instead of brightness)+(1 for down / 2 for up)), the limits are not respected.  Same with on the UI.  I kind of think that, on the UI, it's fine - if someone wants to dig in and say "I really need my contrast maxed out right now," that should be fine.  However, for the key commands, it would be nice if it was restricted, or, at least, given the option via a checkbox or something.

Otherwise, I'm using Lunar every day and it certainly beats using automator services and rewriting code if I want to change or tweak something.  I write enough code (Ruby, though) as it is :)

Nice work mate.

**Comment by alin23** [comment]
Hey thanks for the detailed response! Yes, I'm aware of the update issue. I migrated to edDSA keys and forgot that I have to sign the updates with both the new and the old key to keep the chain of trust. I suspect the DMG problems is related to this.

I think you're right about the up/down hotkeys, they should also be capped. I see them mostly as fine tuning between the percentage hotkeys so it makes sense that they do the same thing. Next update will include this ^_^
