### ISSUE TITLE
macOS Big Sur - All good except for media key override

### ISSUE THREAD

**Issue by Mic238** [alin23/Lunar#132]
Hi Alin,

This is not really an issue, more a report on the new macOS Big Sur. Everything seems good at the moment, the adjustment are slower than the older os, just like all other apps (system issue I reckon). The media key override doesn't work, which is expected, as all other kernel extensions are dead on the new os (Apple changes the way how kexts are installed and loaded, need update from the plugin side). Overall it's pretty much working and usable on Big Sur. 

The os itself is still buggy and break a lot of things, luckily lunar isn't one of it.

Spec: Mac mini 2014 with external Samsung S24E390 Monitor.

Thanks.
Mic

**Comment by alin23** [comment]
Hi @Mic238 ! Media key override works for me. There is no kext used for this functionality, just the old CGEventTap that's been around since OSX 10.4. 

Maybe its a permission issue on your side. 
Try going into Security and Privacy preferences, then Accessibility and then uncheck and re-check the Lunar checkbox and restart Lunar.
![CleanShot 2020-06-26 at 09 13 31@2x](https://user-images.githubusercontent.com/3819725/85826599-7f2abb00-b78d-11ea-9bd5-49576ce78937.png)

Slowness might be from the whole system, I also experience it sometimes and seems to be system-wide when it happens.

**Comment by Mic238** [comment]
No luck, are you running the Big Sur 11.0 dev beta or Catalina 10.15? It was fine on Catalina but not on big sur. 

Now this is probably a bug on big sur, the manual/location mode switch doesn't work on the main panel, and on quick action dropdown when I switch manual and location mode, the brightness/contrast number update, but it's actually not sent to monitor, eg not updating the actual brightness/contrast on screen.

**Comment by alin23** [comment]
I'm on latest Big Sur. I just tested again and media keys really work. I'm using latest Lunar 3.2.3 as downloaded from https://lunar.fyi , no local changes whatsoever.

Indeed, clicking on the mode toggle in the Lunar main window doesn't work, that's weird. 

The quick actions work properly for me though, as soon as I click on an automatic mode like Sync or Location, the brightness is instantly adjusted on the external monitor.

Maybe there is something else overriding the media keys for you. Or maybe try disabling and re-enabling the media keys option:
<img width="894" alt="CleanShot 2020-06-26 at 09 48 21@2x" src="https://user-images.githubusercontent.com/3819725/85828971-3295ae80-b792-11ea-8a80-f73612295d6d.png">

**Comment by Mic238** [comment]
I got lunar restarted and quick actions works now, probably a random jam again. My monitor doesn't like 5 changes in a second and could be not responding to dcc, that looks like it's not working. Individual monitor thing, 

But media key override still not functional. Can confirm on 3.2.3 and no other app overriding it.

**Comment by alin23** [comment]
* Do you keep the cursor on the external monitor when pressing the brightness keys? 
* Did you also try to press fn+brightness keys to test if the function keys are first? 
* Is the brightness OSD not showing up or are the values in the Lunar UI not updating when pressing the brightness keys?

This is what happens on my side when I press the brightness keys:
![lunar-media-keys](https://user-images.githubusercontent.com/3819725/85853514-50c3d480-b7bb-11ea-8cf4-12e763f28c47.gif)

**Comment by Mic238** [comment]
Mac mini, only single external monitor. OSD not shows at all and value not updating at all. Media keys are media keys not function key, Fn+f1/f2 is my current solution as a hot key. 

PS: earlier workaround with Karabinder fails because they use kext and it brakes.

**Comment by Mic238** [comment]
I tried open the lunar package - show package content - Mac OS - lunar, and that way the media key works. But double click lunar/start with system it doesn't. Pretty weird.

**Comment by alin23** [comment]
So it is a permission error.. Maybe quit Lunar and try to remove it from the accessibility list then launch it again, and make sure it is in /Applications. It should ask for permissions.

**Comment by Mic238** [comment]
Yes that's correct, but not under accessibility. It's input monitoring that is not right. Removing and re-add solves the problem.

**Comment by alin23** [comment]
So everything works in the end 😊 I'll think of a better way to handle this in the future. I'll see if this permission error can be detected and at least let the users know about what they can do.

**Comment by Mic238** [comment]
Yes! The text in periodically read monitor value can be updated as well. Unsupported monitor would return read fail on terminal and freeze the monitor. But the app and system are fine. Can add a parameter for monitor about no read support and prevent the app keep sending read request and crash the monitor

**Comment by alin23** [comment]
There already is a logic for stopping read requests if there are more than x failed consecutive reads. But that counter is reset on every app relaunch because the hardware setup might have changed between restarts and we can't verify that.

So if you would have had Lunar running for a few minutes, that lag caused by the reads would have stopped after a while.
For other GPUs, reads cause kernel panics and you have to force reboot the machine causing you to lose any unsaved work, that's why that ugly message is under that option.
