### ISSUE TITLE
Lunar Bug

### ISSUE THREAD

**Issue by Edger** [alin23/Lunar#134]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *MacBook Pro 2015*
    *Bartender 3.1.6*

# Issue description:
*Bartender  can not control Lunar, shown as below.*

<img width="487" alt="截屏2020-06-30 09 29 30" src="https://user-images.githubusercontent.com/18591042/86072762-f2e20600-bab4-11ea-8fb7-be698c29270e.png">

**Comment by alin23** [comment]
Thanks for the report @Edger ! 

Although I don't see how this could be a bug in Lunar. The menu bar icon is shown using standard Cocoa APIs used by every other macOS app, there's nothing hacky or custom about it. 

You can see here that all it does different is add a tracking area so that it knows to show/hide the Quick Actions popover when  you hover the mouse over the icon:
https://github.com/alin23/Lunar/blob/16e2d4c8bf5f9b73141d69d958df442c8f9ca8ca/Lunar/AppDelegate.swift#L458-L463

And you can see in my screenshot that this doesn't happen on my machine so it's probably related to something in your Bartender settings. Maybe try to uninstall it completely using something like CleanMyMac and reinstall it.
