### ISSUE TITLE
Lunar Diagnostics Report [EB9CAD82D1F6B749339795E48F5101D0D4E9215178B5DA368B9AE673F4395784] [3.2.3]

### ISSUE THREAD

**Issue by fedorbozik** [alin23/Lunar#135]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    Yes

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
   iMac (Retina 5K, 27-inch, 2017)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C to USB-C

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
Whenever I am using my external monitor and my mouse is on the desktop of that monitor, and I change the brightness it works, but it only changes the brightness of the external monitor and then refuses to sync the two displays brightness levels no matter what I do, it only works again after a full computer restart. Is there something I can configure that disables this behavior?

**Comment by fedorbozik** [comment]
I think I might have fixed the issue with enabling the advanced feature called "Read external monitor brightness periodically"

**Comment by alin23** [comment]
Syncing works only in one direction: **built-in monitor -> external monitors**

Changing the brightness of the external monitor directly is for adjusting the offset in case the sync algorithm curve isn't correct for that specific brightness (e.g. the monitor brightness is synced with the built-in one but it is a bit lower than you would like so you increase just the external monitor brightness and Lunar knows to adjust the curve)

If you open the Lunar Configuration UI you'll see that when you change the brightness with the cursor on the external monitor, what actually changes is the brightness/contrast offset:
![CleanShot 2020-06-30 at 10 54 10@2x](https://user-images.githubusercontent.com/3819725/86099508-3a21c400-bac0-11ea-928d-69d53e064489.png)

The `"Read external monitor brightness periodically"` setting is nice to have enabled if it works for your setup (it rarely works) because in this way Lunar can detect external changes to the brightness, like when you change the brightness through the monitor physical buttons/controls. If Lunar can do that, it won't always try to override externally adjusted brightness and the user experience would be a bit better.
