### ISSUE TITLE
Scroll Doesn't Work 

### ISSUE THREAD

**Issue by chelseas** [alin23/Lunar#140]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
  macbookpro 2018

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    phillips brilliance PHL 272P7VU

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
   usb c to usb c

- Using an USB Docking Station or Hub:
  no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
   tried any/all

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
scroll doesn't work when trying to adjust the brightness with the dropdown menu / popup that pops up from the top bar of my mac when lunar is running. also the scroll controls in the main UI are really non-intuitive

**Comment by alin23** [comment]
It's possible that the monitor was detected as non-responsive and that's why the popover doesn't respond to scroll events. Or maybe the popover can't get focus because of something else requesting a higher focus level just below the menu bar. I really can't know, but I think it's related to your setup.

The scroll controls can also be finely adjusted using up/down arrows if you want. Scrolling to adjust is what I personally like and I'd like to keep it that way. I'll try to add text editing to the fields for even faster fine tuning if that's what you would like.

**Comment by chelseas** [comment]
hmmmm. i like scroll controls too. i use better snap tool. maybe this could be related? not sure. good to know about the arrow keys. right now i have been using the "0% 25% ..." etc. controls

**Comment by alin23** [comment]
It's possible, any software that controls the window manager and can override trackpad gesture can interfere with this. I'll close the issue now as it doesn't seem to be a bug in Lunar but feel free to post updates here.
