### ISSUE TITLE
Sync mode sometimes stops working

### ISSUE THREAD

**Issue by fireteam99** [alin23/Lunar#143]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro (Retina, 15-inch, Mid 2015) running macOS Catalina 10.15.3 (19D76)

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Dell U2415

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
   miniDisplayPort to DisplayPort

- Using an USB Docking Station or Hub:
    no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    yes

# Issue description:
The external monitor will occasionally disconnect from the sync mode and switches back to the default manual brightness and contrast. Attempting to switch to manual then back to sync will not resolve the issue. The issue persists even when restarting lunar. The only way to fix it is to physically disconnect the monitors and reconnecting them.

**Comment by alin23** [comment]
Sounds like something caused by the monitor itself. Do you have any Dell specific software installed in your system?
If only a hardware reconnection fixes the issue then I'm sure it's not a bug in Lunar.

**Comment by fireteam99** [comment]
I don't have any Dell specific software installed but that is a good point.

**Comment by ozkanaltuner** [comment]
I also have Dell U2718Q monitor and sync is not working properly. I think it was running well the first time I've installed Lunar, and when the laptop slept, I was not able to make it work again. There seem to be sync problems with the built-in display.

**Comment by alin23** [comment]
I also have this issue where Lunar has to be forced to sync after sleep. I do that by changing the brightness and contrast manually and then re-enabling Adaptive mode
![CleanShot 2020-09-18 at 10 51 29](https://user-images.githubusercontent.com/3819725/93571324-f80c6e00-f99c-11ea-9220-7c44f8252966.gif)

I haven't yet been able to reproduce this in debug mode so I have no fix yet.

**Comment by eyv** [comment]
I have this issue as well using U3219Q.

**Comment by mplesec** [comment]
Also using a U3219Q. I've noticed this happens when I open a bright page while in a dark room.

Pretty basic question, but is it possible that since the bright screen brightens me in front of it, the sensor picks that up as a signal that it's brighter in the room and then increases both the macbook's and external display? And the whole thing goes into a loop where it just keeps slightly increasing the brightness since it always picks up a brighter signal.

**Comment by aMoniker** [comment]
This also happens to me using an LG Ultrafine, especially after sleep mode.

**Comment by SAGV** [comment]
Same with LG Ulrtrafine on macos 10.15., It just resets itself to minimal possible brightness and stays there till I reconnect the monitor

**Comment by alin23** [comment]
Sorry for having no update on this. Next Monday I'll be switching to a three-day workweek schedule at my daily job so I'll have more time to work on Lunar.

**Comment by SAGV** [comment]
@alin23 wow, this is a big commitment, I hope it is a weighted decision. Anyway, thanks for it  ❤️

**Comment by eyv** [comment]
Having this issue with U3219Q and U2720Q(M)

**Comment by alin23** [comment]
I think I managed to solve this, I have been testing a fix for the last week and looks pretty solid.
I just got my M1 Macbook so I'll also try to see if it is possible to make Lunar work on this (right now it looks impossible, but I'll try my best).

Hopefully at the beginning of the next year, Lunar 4.0 will be launched with all the fixes and some very useful new features!

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
