### ISSUE TITLE
Lunar Diagnostics Report [435D8764E36463402C50B424A896194F4406D987D97B0E9424EE4B7F2BEE8577] [3.2.3]

### ISSUE THREAD

**Issue by sjhoglund** [alin23/Lunar#145]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Pro 2019

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    Two Thunderbolts - one connected directly to laptop via USB-C to Thunderbolt 2 and the monitors are daisy chained

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
Not adjusting screen brightness or any other settings

**Comment by alin23** [comment]
Lunar uses a special private API for adjusting brightness on monitors vendored by Apple. In your case, it sounds like this API doesn't work for some reason. 

You can try to rename the monitors to something other than **Thunderbolt** by clicking on their name in the Lunar UI. If the name doesn't contain the word **Thunderbolt** then Lunar will fallback to the DDC method.

Sounds like this auto detection has some issues so I'll try to add a toggle for it instead of making people change the monitor name.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
