### ISSUE TITLE
Minimizing on external display leads to screen lag and flicker

### ISSUE THREAD

**Issue by andrewmccullough** [alin23/Lunar#146]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *MacBook Pro 2019, 13"*

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    *Dell U2415*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *HDMI to Anker USB-C adapter to USB C*

- Using an USB Docking Station or Hub:
    *Yes, Anker 5-in-1 USB-C*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Manual*

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
*With Lunar open, when minimizing windows (particularly when there are multiple windows open) on my external display, I will experience lag and even the screen turning black momentarily. This occurs when reopening minimized windows, too.*

**Comment by alin23** [comment]
Sounds like you have a monitor setup with slow response and it is causing the kernel to pause a lot.

Try to disable **Read external monitor brightness** and **Smooth Transition**

![CleanShot 2020-07-15 at 22 10 04@2x](https://user-images.githubusercontent.com/3819725/87585593-ff3aa580-c6e7-11ea-9ccc-8086e521cb31.png)
![CleanShot 2020-07-15 at 22 11 14@2x](https://user-images.githubusercontent.com/3819725/87585702-24c7af00-c6e8-11ea-8fe4-b3a727303170.png)

I can't really pinpoint what is the culprit here. It can be the GPU, it can be the USB-C hub, even the cable can cause this. The monitor can also cause slowness but I've had multiple reports of Lunar working perfectly with this specific monitor so I'm not sure about this.
