### ISSUE TITLE
How Lunar works?

### ISSUE THREAD

**Issue by dannluciano** [alin23/Lunar#148]
### Name of the feature

How Lunar works?

### What problem does this feature solve?

Congratulations for the project. Can you explain how Lunar works? Or how you find this logic?

**Comment by alin23** [comment]
Hi! Thanks!

Lunar works by sending messages to monitors through a protocol called Display Data Channel, or DDC for short. 
These messages are in essence, precisely timed electrical pulses which travel through the cable that connects the monitor to the Mac device. The timing of the pulses is defined by the I2C protocol, and the GPU does all the heavy lifting for us.

The messages can look something like this:
```js
{
  control_id: 0x10
  new_value: 90
}
```
Where `0x10` is the control ID for brightness, defined in the Monitor Control Command Set specification, and the `new_value` is the brightness value we want the monitor to have.

This message is sent to the GPU, along with a unique display ID, which forwards it through the cable to that specific monitor. 

This is where Lunar stops working for some people, because between the GPU and the monitor there can be a number of hops like:
* cables that use the DDC pin for something else (like Dual DisplayPort)
* hubs/docks/adapters that don't forward the message at all
* monitors that decide to not do anything with this message
* proprietary protocols like DisplayLink that don't support DDC

If everything works properly, the monitor should react to that message by setting the value Lunar sent.

Some links if you want to go deeper:
* [ddcctl](https://github.com/kfix/ddcctl) - this is where I got the DDC implementation over which I built Lunar
* [MCCS Specification](https://milek7.pl/ddcbacklight/mccs.pdf)
* [DDC protocol explained](https://www.nccgroup.com/globalassets/our-research/uk/whitepapers/hdmi_-_hacking_displays_made_interesting.pdf)
* [I2C](https://www.circuitbasics.com/basics-of-the-i2c-communication-protocol/#:~:text=I2C%20is%20a%20serial%20communication,the%20master%20and%20the%20slave.)

**Comment by dannluciano** [comment]
Thanks for your answer.
And about the changes on bright and contrast over the day.
You use any math function?
You use any study/paper or is your preferences or feeling?

**Comment by alin23** [comment]
For `Sync` mode, the mathematical function is a simple linear interpolation of the built-in display brightness, where the factor is adjustable through the **Offset** setting:
![image](https://user-images.githubusercontent.com/3819725/88626257-03d16780-d0b3-11ea-921e-49b216b71188.png)

You can play with the _f_ factor here to see how the curve is computed: https://www.desmos.com/calculator/zciiqhtnov

The default values are what should work for most people but the users are free to adjust the curve however they want using the **MAX/MIN** limits, the **Offset** values and the **Brightness clipping** setting.

For `Location` mode, it is a linear interpolation of the current sun elevation at your location, adjustable using the **Curve Factor** value. This curve is also adjustable using the **Noon duration** and **Daylight extension** settings:
![image](https://user-images.githubusercontent.com/3819725/88627003-4b0c2800-d0b4-11ea-9cdb-27d3ad45a98c.png)

macOS and the very sensitive Ambient Light Sensor of the Macbook does most of the work in finding the right brightness value for us so we don't have to over complicate things with studies and papers. I'm sure the Apple engineers read enough papers and did enough lab experiments to find the right adaptive curve, so I'm just using their work. 😅

**Comment by dannluciano** [comment]
Thanks! I want replicate this behaves in Linux.

**Comment by dannluciano** [comment]
Thanks! I want replicate this behaves in Linux.

**Comment by StefanLobbenmeier** [comment]
> Thanks! I want replicate this behaves in Linux.

Sorry to comment on a closed issue, but I guess what you are looking for is https://github.com/rockowitz/ddcui - I think it would be best to first look into extending that instead of starting from scratch.
