### ISSUE TITLE
External Display standby

### ISSUE THREAD

**Issue by gargs** [alin23/Lunar#149]
### Name of the feature

External Display Standby/Power Control

### What problem does this feature solve?

The sync and manual brightness control provided by Lunar is exceptional! Sometimes, though, you really would like to power down (change to standby) the external display to better enjoy movies or games. It would be great if Lunar could be extended for this.

### How should the feature work

There could be a hotkey or a menu setting to toggle the standby status of the externally connected display(s).

### Note

I think the DDC interface does provide a way to provide a power setting. I tried the ddcctl command line interface to pass on the power, and while my external display is able to power down or goto standby, I cannot figure out how to power it back on using the command line.

**Comment by alin23** [comment]
Hi @gargs ! I admit this would be a useful feature but this is not the first time it has been requested. 😅

Lunar does nothing different than what ddcctl does. In fact 90% of the DDC code inside Lunar comes from the ddcctl repository. 

So as you have already noticed, there is no obvious way to wake up the monitor from standby, and this would make for some very angry users that will think Lunar bricked their monitor.

This probably happens because, for the monitor, standby means _stop polling for DDC messages_ and this is not fixable in software. (well not in our software, it could probably be fixed inside the monitor firmware code which we can't modify)

**Comment by gargs** [comment]
Hey @alin23 ! Thanks for the speedy reply. I tried to search for dupes, but must have missed them. Anyway, thanks for the explanation. It makes a lot of sense. Thanks! I guess a personal project for me now is to overlay the external display with an opaque black view! 😄

**Comment by alin23** [comment]
If it helps in any way, <kbd>Control</kbd>+<kbd>Command</kbd>+<kbd>0</kbd> will tell Lunar to set brightness and contrast to the minimum values for all external monitors. It is not black black, but it is a quick way to solve this

**Comment by alin23** [comment]
The limits for that are configurable on the Configuration page in Manual mode:
![image](https://user-images.githubusercontent.com/3819725/88662024-1020e900-d0e2-11ea-9deb-f36c6fbb39c2.png)

**Comment by gargs** [comment]
Great! Thanks for the help! And also thanks for building this amazing app.
