### ISSUE TITLE
Add delay after waking up

### ISSUE THREAD

**Issue by maxgashkov** [alin23/Lunar#150]
### Name of the feature

Delay after waking up (in seconds)

### What problem does this feature solve?

Secondary monitor connected to my iMac, Asus VG27A, wakes up with a significant delay after the main one, up to 2-3 seconds later, which leads to 'Non-responsive DDC' state. 

### How should the feature work

1. Lunar should not issue any DDC commands while the monitor is off (it seems that now it's not the case, because sometimes secondary monitor wakes up, possibly due to Lunar reacting to ambient sensor data).

2. Upon main monitor wake up, if the setting is configured, Lunar should delay syncing state until configured timeout elapses.

**Comment by maxgashkov** [comment]
(I'm not quite sure that problematic behavior is not caused by a bug or some kind of misconfiguration on my part. I will be happy to provide additional data if needed.)

**Comment by alin23** [comment]
There isn't a way to detect whether one of the monitors hasn't waken up yet. Lunar receives events from macOS when the display configuration changes, and if that not-yet-waken-up display ID is in the configuration sent by the system, Lunar will consider it a working display. I don't get any other information inside that event.

I will try to check if `CGDisplayIsActive` returns useful information for this case, but it will be a bit hard to test because I don't have a monitor with such a slow wake up time. Maybe I can send you a beta version with that check to see if it helps

**Comment by maxgashkov** [comment]
I can check with beta version, sure.

I was thinking about this a bit more and I wonder if there is a drawback in trying to send DDC commands even if the device is unresponsive? I'm noticing that this issue tends to clear itself after a while, and if Lunar will retry sending commands more frequently, this will be a non-issue (at least for me).

**Comment by alin23** [comment]
Lunar has logic to stop sending DDC commands after a number of DDC messages were reported as not received. That's what Non-responsive DDC means actually, it means that Lunar has given up on trying to control that monitor to avoid hogging the GPU and blocking the system kernel unnecessarily.

I can add a long polling time for non-responsive monitors, like try to send a command every 5 seconds and when one of those commands is received, the non-responsive flag should be disabled automatically. What do you think about this idea?

**Comment by maxgashkov** [comment]
That sounds like it will solve my particular problem, thank you! Looking forward to test beta build when you're ready.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
