### ISSUE TITLE
Lunar Diagnostics Report [6F061F75EBB0191FBF7D35FFC069993E8E70893C572B5E269C7ECDC13572649D] [3.2.3]

### ISSUE THREAD

**Issue by uhlume** [alin23/Lunar#151]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    no

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro mid-2015

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    miniDisplayPort-to-DisplayPort

- Using an USB Docking Station or Hub:
    no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
Lunar doesn't appear to affect external monitor brightness/contrast settings. (Samsung U28E510, Mid-2015 MBP w/  Radeon R9 M370X 2 GB)

**Comment by alin23** [comment]
@uhlume is that an external GPU that you are using? DDC doesn't always work with external GPUs

**Comment by alin23** [comment]
My bad, it seems to be a built-in GPU for 2015 Macbooks. It would be great if you could try https://github.com/kfix/ddcctl#install with the `make amd` command and see if it works for you. 

It would be a good way to check if the GPU detection feature of Lunar is the issue here.

**Comment by uhlume** [comment]
Thanks for the quick response! It's closing on 2am, here, so I'll need to try building the ddcctl executable in the morning and get back to you.

Thanks again.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
