### ISSUE TITLE
Lunar Diagnostics Report [F6DD79537FCCDCC0B9ED047EF6A0FA3923C344544112EC5AA74560BB2A241384] [3.2.3]

### ISSUE THREAD

**Issue by homeowmorphism** [alin23/Lunar#152]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    Yes

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Pro 2018

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C

- Using an USB Docking Station or Hub:
    no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
Lunar syncs with built-in display but then immediately returns to 100% brightness/contrast.

**Comment by alin23** [comment]
Is it possible that your monitor has some setting that does this 100% override?
I don't see how Lunar could go to 100% in sync mode, without the builtin brightness being changed.

Actually there is a way: #86 
If HDR content is causing this for you (HDR videos, using a HDR enabled video editor) then there is no solution for that yet.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
