### ISSUE TITLE
Option to disable system tray icon

### ISSUE THREAD

**Issue by dguendisch** [alin23/Lunar#153]
### Name of the feature
Disable System Tray

### What problem does this feature solve?
I'm "only" using Lunar for manually inc/dec brightness of my non-apple monitor with the hotkeys on my apple keyboard.
Therefore I don't need the system tray icon and would prefer to safe that precious tray space.
An option to disable it (of course while lunar is still running) would be great!
(if you want to configure something you could still launch Lunar app manually, i.e. betterTouchTool works that way and many other utilities)

**Comment by patrickrushton** [comment]
+1 I need to declutter my menubar and I use Lunar almost entirely via shortcut keys since getting it set up how I like it.

My vote would be to implement Lunar as a preference pane in System Preferences, in a similar way to utilities such as Smart Scroll.
![lunar pref pane](https://user-images.githubusercontent.com/6472595/91576795-1c4dcf80-e948-11ea-90cb-1754ee31f974.png)

**Comment by alin23** [comment]
Closing in favor of #239

This is already implemented, just needs release.
