### ISSUE TITLE
Lunar Diagnostics Report [BFD26ED89AAE5A16FDADD7811144D223D2988C287F2A861FD87D789F45A1A07F] [3.2.3]

### ISSUE THREAD

**Issue by Wouter01** [alin23/Lunar#154]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    No. The screen flickered a couple of times (lower part of the screen).

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
   MacBook Pro 13" 2018

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI-to-HDMI

- Using an USB Docking Station or Hub:
    Yes, an Anker usb-c hub (so HDMI-to-USB-C)

- Lunar mode used (check it in the top-right corner of the Lunar interface)
   Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
The screen brightness doesn't change. I've seen the lower part of the screen flicker a couple times but there was nothing actually changed. Changing contrast also doesn't work.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
