### ISSUE TITLE
Lunar Diagnostics Report [C20FF386C3581AD0BA4D658D119119DA25D52EB20F3364CF227C08D57299CA9D] [3.2.3]

### ISSUE THREAD

**Issue by shayonpal** [alin23/Lunar#156]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    *No*

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *MacBook Pro (16-inch, 2019)*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *USB-C to HDMI*

- Using an USB Docking Station or Hub:
    *No*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Sync Mode*

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *Can't compile*

# Issue description:
*Monitor model is Acer EB321HQU. None of the options worked for me, neither brightness, nor contrast.*

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
