### ISSUE TITLE
Lunar Diagnostics Report [5BE96D5F3D13CE3F33E3AB9B26E77CD330C58DBAB42042F8BBCF366C8CDD0AEF] [3.2.3]

### ISSUE THREAD

**Issue by IvoCrnkovic** [alin23/Lunar#159]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Pro 2018

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    Thunderbolt Display -> Thunderbolt 2-> Thunderbolt 3 

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Diagnostics was not able to change brightness in any mode.  Mode used for this report was Sync.

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
As far as I can tell, Lunar does not change brightness/contrast on my 2 thunderbolt displays at all.  Manually changing the brightness in preferences doesn't do anything, neither did anything else.

**Comment by alin23** [comment]
T

**Comment by IvoCrnkovic** [comment]
I changed the names of the monitors and restarted lunar, still couldn't get it to change the brightnesses at all.  Ran diagnostics with same result.

**Comment by alin23** [comment]
Yes, there is a bug right now in Lunar that always overrides the custom name. I'll add an Advanced option so that users can disable that Apple display logic for monitors that don't support this.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
