### ISSUE TITLE
Clarifications about the UI

### ISSUE THREAD

**Issue by arpachain-admin** [alin23/Lunar#16]
The change is not reflected to the screen and sync mode changes the screen's contrast to unreasonable value. The UI is not displayed properly.

**Comment by alin23** [comment]
Can you please give me more details, maybe with some pictures? I'm working on Mojave since the first versions of Lunar and never had any problem. I'm sure it's not Mojave's fault here, it might be an incompatibility issue with your system configuration or monitor.

Please let me know of the following:
1. On what device are you using this (Macbook Pro/Air/12inch, iMac, Mac mini etc.)
2. How is your monitor connected to your device (Direct HDMI/DisplayPort/USB-C, through a dock etc.)
3. What monitor are you using
4. If you have a Macbook, are you using it with the lid closed or not
5. Some screenshots with the UI that you noticed is not displayed properly
6. What change is not reflected to the screen

**Comment by callzhang** [comment]
1. MBP-17 13'
2. USB-C & HDMI
3. ViewSonic VS16829
4. I am using it with lid open
5. I am wrong with the UI, there is a "Plus" button at exception that I thought is a bug.
6. Neither brightness or contrast was changed immediately after I scroll over(change) the number. But occasionally the brightness or contrast will change. In addition, I changed the mode to Sync and Adaptive, but the main monitor's brightness is not synced to the external one.

**Comment by callzhang** [comment]
Some follow up question:
1. What is the default contrast value? I couldn't return to the original value after its sudden/occasional change.
2. What is Sync and Adaptive mode mean?
3. Can you include a manual or something explaining the curves and offset?

**Comment by alin23** [comment]
There is no default contrast value. Each monitor has a default from the factory but it always depends on the monitor's settings.

In Sync mode and Location mode, changing the limits for brightness/contrast won't automatically change the brightness on the monitor. Those are just settings for the adaptive algorithm which I'll explain below. If you want to change the values immediately, you can try the Manual mode where there is no automatic change in the background.

# Sync Mode
Lunar polls the built-in display brightness every second and whenever the brightness changes (either because of the light sensor or changed manually) then Lunar changes the external monitor's brightness to match the built-in one.

The new brightness is calculated using a formula like: 

<a href="https://www.codecogs.com/eqnedit.php?latex=\large&space;\frac{\frac{perc}{100}&space;*&space;(max&space;-&space;min)&space;&plus;&space;min}{100}^{curveFactor}&space;*&space;100&space;&plus;&space;appPerc" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\large&space;\frac{\frac{perc}{100}&space;*&space;(max&space;-&space;min)&space;&plus;&space;min}{100}^{curveFactor}&space;*&space;100&space;&plus;&space;appPerc" title="\large \frac{\frac{perc}{100} * (max - min) + min}{100}^{curveFactor} * 100 + appPerc" /></a>

Where:
* `perc` is the built-in display brightness
* `min` and `max` are the limits you set in the Lunar display page
* `curveFactor` is the Curve Factor from the settings page
* `appPerc` is the App Exception offset in case the frontmost application is present in the exception list. Otherwise it is zero.

The *Adaptive* button below the monitor is there so that you can stop Lunar from automatically adapting specific monitors in case you have multiple monitors.

**Comment by callzhang** [comment]
Thanks for the reply. However:
1. In manual mode the brightness doesn't change immediately when I change the number. (but rather change suddenly and radically)
2. In Sync mode the brightness doesn't change according to the system brightness or environment.
3. What does "Adaptive" mode mean?

**Comment by alin23** [comment]
1. The brightness isn't supposed to change at every small scroll/change of the number. It will change only after you stopped scrolling for a little while. The protocol used for making the brightness changes isn't fast enough to make these changes fast and smoothly.
2. I don't know what could be the problem here. Maybe you have too strict limits. 
Try doing this:
    - **Make sure you have Sync mode on**
    - **set Adaptive mode on, Min brightness to 0 and Max brightness to 100 like so:**
![image](https://user-images.githubusercontent.com/3819725/55274733-63afd680-52e4-11e9-9ca5-5ffd0793aa53.png)
    - **set brightness offset and contrast offset to 0 like so:**
![image](https://user-images.githubusercontent.com/3819725/55274746-95c13880-52e4-11e9-8492-aaa6cba0bc07.png)
    - **clear the app exception list like this:**
![image](https://thumbs.gfycat.com/UniqueDownrightCockatiel-small.gif)
    - **cover the light sensor for about 10 seconds and see if the Macbook built-in display darkens**
    -  **Lunar should notice this change in brightness and replicate it on the external monitor**
*You can find the Macbook light sensor right near the camera:*
![image](https://i.imgur.com/zUKtgmQ.jpg)
3. Adaptive mode means that Lunar will change the brightness automatically based on the selected algorithm: Sync or Location.
Without Adaptive mode, you have to change the brightness yourself.

**Comment by edeis53** [comment]
Lunar has absolutely zero effect on my external display in any mode or manual setting. Is there any possibility it has to do with the HDMI cable or USB->HDMI adapter?

Spec:
2018 Macbook Pro 13", latest Mojave 10.14.4
Monitor: Acer et241ybmi 23.8" 
-DDC/CI option is set to ON via the montor's onscreen menu.

**Comment by alin23** [comment]
What kind of USB->HDMI adapter are you using? Most of this stuff doesn't implement DDC message passing so that's why Lunar won't work. Even some cables don't work. 
For example I have a $30 HDMI-to-USB-C cable (no adapter, just a cable) and it messes up DDC completely. No matter what message I try to pass through it, the monitor just flickers a little and that's it.

Unfortunately it's hard to guess what works from product descriptions, DDC compliance is rarely mentioned.

**Comment by edeis53** [comment]
@alin23 I have a Raycue USB-C Hub/HDMI adapter.
Link: https://www.amazon.com/RayCue-Adapter-Charging-Notebook-Tablet/dp/B0795DWPFJ

I dug up in another forum a mention a few years back about similar issue with DVI->HDMI adapters or something of the likes and the conclusion was that the adapter is not bi-directional. Another poster was using an adapter that was bidirectional (and was mentioned in the product description) and DDC control worked.

I have an old 2013 Macbook Air with a display port to HDMI cable setup on a different monitor/desk and it worked no problem with Lunar! 

It's a real shame how many manufacturers don't comply with the HDMI specifications, just to save a few pennies on not include a pin or two. 

I've ordered a dedicated USB-C to HDMI cable and will see what happens. I contacted several sellers online and asked them if it supports the DDC protocol and if it's bidirectional and they all replied, no it's only USB-C to HDMI, lol. They don't have a clue.

I anticipate many issue being opened due to this. Perhaps it might be beneficial to collect a list of cables/adapters that do support DDC.

**Comment by alin23** [comment]
@edeis53 I'm working on updating the Lunar website with more info about all this stuff. As you have predicted, I'm getting tired with answering the same questions 😄 

It's hard to find the time for this though. Please let me know if your new cable will work, I'll also ask around and try to compile a list with inexpensive cables/adapters that work as that is the biggest pain point I see.
