### ISSUE TITLE
Lunar Diagnostics Report [53407C45B6D38D5D3C99ED309722C1E5A22AF84AA9E02F16A8A7F3E84DAA7E60] [3.2.3]

### ISSUE THREAD

**Issue by nickgggg** [alin23/Lunar#160]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    one external display yes, the other no. 

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    2015 27" iMac

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
   HDMI to miniDisplayPort

- Using an USB Docking Station or Hub:
    amazon basics hdmi to miniDisplay

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
only 1 of my 2 external displays changed brightness

**Comment by alin23** [comment]
Looks like a hardware connection problem. There's not much you can do other than trying a different adapter/cable for the monitor that doesn't work.

I'm curious, does the non-working monitor start working if you swap the connectors on the back of the iMac? 

If that's the case then you can be certain the problem is with the iMac GPU not routing the DDC messages to both monitors and no adapter can fix that.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
