### ISSUE TITLE
Lunar Diagnostics Report [7A4A550D467BED642564C71E95C6D984925120A0821CDC65910F1C07099660F9] [3.2.3]

### ISSUE THREAD

**Issue by Canorus** [alin23/Lunar#162]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
only one of them

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
Mac mini 2018

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    Monitor - (HDMI - DP) - eGPU(Radeon 580)
    Monitor - (HDMI - DP) - eGPU(Radeon 580)
    HDMI —— Main display 

- Using an USB Docking Station or Hub:
No displays are connected through Docking station or hub

- Lunar mode used (check it in the top-right corner of the Lunar interface)
Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl

it didn't work as expected

```
Mac-mini-2020:ddcctl canor$ ./ddcctl -d 1 -b 50
D: NSScreen #1007314882 (1600x900 0°) 92.00 DPI
D: NSScreen #487120904 (2560x1440 0°) 123.00 DPI
D: NSScreen #487120905 (2560x1440 0°) 123.00 DPI
I: found 3 external displays
I: polling display 1's EDID
I: got edid.name: HP W2072a
I: got edid.serial: CNC207Q44B
D: action: b: 50
D: setting VCP control #16 => 50
Mac-mini-2020:ddcctl canor$ ./ddcctl -d 2 -b 50
D: NSScreen #1007314882 (1600x900 0°) 92.00 DPI
D: NSScreen #487120904 (2560x1440 0°) 123.00 DPI
D: NSScreen #487120905 (2560x1440 0°) 123.00 DPI
I: found 3 external displays
I: polling display 2's EDID
I: got edid.serial: 0000000000000
I: got edid.name: HDMI
D: action: b: 50
D: setting VCP control #16 => 50
Mac-mini-2020:ddcctl canor$ ./ddcctl -d 3 -b 50
D: NSScreen #1007314882 (1600x900 0°) 92.00 DPI
D: NSScreen #487120904 (2560x1440 0°) 123.00 DPI
D: NSScreen #487120905 (2560x1440 0°) 123.00 DPI
I: found 3 external displays
I: polling display 3's EDID
I: got edid.serial: 0000000000000
I: got edid.name: HDMI
D: action: b: 50
D: setting VCP control #16 => 50
```

# Issue description:
brightness on only one of 3 displays are controlled. looks like ddcctl can't detect edid.serial correctly?

**Comment by alin23** [comment]
Hi! Thanks for the detailed report!

HDMI on Mac Mini is known to not work with DDC. I'll close this in favor of #125

I'll hopefully get physical access to a Mac Mini next month to be able to debug this further.

Until then, try DisplayPort if possible.

**Comment by Canorus** [comment]
Hi thanks for the reply

I am aware of the HDMI port on MM not working with DDC, what I was mentioning was about other displays connected via eGPU. Could you take another look into this?

If all displays won't work if HDMI port is occupied please let me know. I'll try to change my hw configuration. Thanks.

**Comment by alin23** [comment]
eGPU is another thing that causes issues with DDC. Different GPUs have different response times and as you can see here, the Intel reply delay is different from the AMD one: https://github.com/alin23/Lunar/blob/master/Lunar/DDC/DDC.swift#L19

It's possible that the GPU is not detected correctly or that the eGPU being external needs a different (higher?) delay value.

Unfortunately it's impossible for me to find the right value without physical access to the device.

You could try compiling ddcctl with different reply delay values until you get something that works: https://github.com/kfix/ddcctl/blob/master/Makefile#L20

Then we can pair to see what GPU name gets reported on your system and tie that to the reply delay you found to be working.

It's also possible that the eGPU can't route DDC messages to more than one monitor, which seems more probable because you said that one of the monitors can be controlled successfully. In that case, the reply delay value can't make any difference.

**Comment by Canorus** [comment]
Oh it's a lot more work than I expected. Maybe I'lll have to begin with digging ddcctl haha

thank you so much for so detailed answer. I'll report here if I find anything useful.
