### ISSUE TITLE
Lunar Bug - Volume change not working

### ISSUE THREAD

**Issue by jpomykala** [alin23/Lunar#164]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
MacBook Pro 2018 13'' with TouchBar 
10.15.6

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
Dell U3415W

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
 USB-C-to-USB-C

- Using an USB Docking Station or Hub:
no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
Hey I noticed that volume is changing on monitor HUD, but it's just 'not working' and the sound stays at the same level. To make it work I need to mute and unmute or change volume by 1 using monitor HUD settings. 

PS How can I help more in resolving this issue? I don't have too much experience in macOS programming but I can help somehow. Could you point me place in the source code to play around with it by my own?

Thanks!

**Comment by alin23** [comment]
The easiest way would be to compile [ddcctl](https://github.com/kfix/ddcctl) and use that to play with the volume on your monitor.

Lunar does the same thing in its code and actually uses part of the ddcctl code for the DDC implementation.

Here is an example of how I used ddcctl to query the volume and then set it to the value 50.

![image](https://user-images.githubusercontent.com/3819725/91960061-196d2900-ed12-11ea-9762-33857118ebb2.png)

There's always the possibility of a limitation in the monitor firmware. If ddcctl still doesn't work then it's possible that we can't make it work in software because the monitor probably waits for hardware button events before setting the actual volume.

**Comment by jpomykala** [comment]
Hey @alin23 thanks for the response. I will play with it, and I will let you know if I will find some solution 👍 
Thanks!

**Comment by jpomykala** [comment]
Hey I tried ddcctl and it's not working U3415W 👎  I'm closing the ticket

**Comment by merchako** [comment]
I'm having a similar issue, so I want to check that I understood what happened. Volume controls weren't working for @jpomykala on his Dell U3415W in Lunar, so he tried to controlling it with DDCCTL directly. When that didn't worked, we learned that the U3415W simply doesn't listen to DDC volume commands, so control from Lunar would be impossible. Do I have that right?

I have two Dell U2415 monitors, so I'm guessing volume control isn't working on them for the same reason.

**Comment by alin23** [comment]
@merchako  yes that is right. Dell didn't implement logic for receiving volume control commands on those monitors.
