### ISSUE TITLE
Lunar Feature - Debounce Brightness Events

### ISSUE THREAD

**Issue by andrewphillipo** [alin23/Lunar#168]
### Debounce Brightness Events

Debounce Brightness Events - it seems currently most changes to the brightness are done after a few seconds - I propose that while brightness is going up and down a whole second (configurable) is waited before changing the brightness. This seems to not be the case now the events merely seem to be delayed, not debounced.

"Debounce: a function, that, as long as it continues to be invoked, will not be triggered. The function will be called after it stops being called for N milliseconds."

### What problem does this feature solve?

I hear about writing these settings can cause issues with EEPROM. Also currently the brightness stutters and feels very inorganic - I'd rather it not fail at smoothly transitioning and just change after that timeout.

### How should the feature work

https://davidwalsh.name/javascript-debounce-function

### Visual description

Well there could be a checkbox to choose this behaviour or the current one?

**Comment by alin23** [comment]
The brightness changes are already debounced for the scrollable field changes. For the Sync mode, the brightness is only changed when the built-in display brightness changes and how often that happens can be controlled using the _Polling interval_ setting:

![image](https://user-images.githubusercontent.com/3819725/91993037-95309b00-ed3d-11ea-80ff-d04ea25338f2.png)

If you want to limit the brightness value writes, make sure to also disable the _Smooth transition_ setting:

![image](https://user-images.githubusercontent.com/3819725/91993208-c3ae7600-ed3d-11ea-9200-43d26b231724.png)

The stutter you experience probably happens because your monitor has a slow response time, this is explained in the _Smooth transition_ help text:

![image](https://user-images.githubusercontent.com/3819725/91993401-ff494000-ed3d-11ea-81e5-697a677b2a95.png)

**Comment by andrewphillipo** [comment]
Sorry! I found the screens now! You already have what I was looking for sorry to waste your time!

**Comment by alin23** [comment]
No worries!
