### ISSUE TITLE
Lunar Diagnostics Report [6E5DEFFC5C3C9841F2D75531202383C5A73F5FEE7ACA89FCB0482351433FCEF7] [3.2.3]

### ISSUE THREAD

**Issue by therealhoodboy** [alin23/Lunar#173]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro 2018, 15"

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI -> HDMI

- Using an USB Docking Station or Hub:
    YES

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
I´m using 2 EIZO Foris FS2434 for work. Unfortunately, I cant change the brightness, contrast or else. Tried also with connecting my screens via USB, but it didn´t help. 
Additionally, I restarted my Mac a few times, but also, didn´t work.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
