### ISSUE TITLE
How to completely delete Lunar

### ISSUE THREAD

**Issue by MarkYangjiayi** [alin23/Lunar#18]
Hi,

Great app you have developed, but its not actually what I expected so I tried to delete it.
However the effects of Lunar won't go away even when I deleted it. Is there any way I can get rid of it completely?

Thanks in advance!

**Comment by alin23** [comment]
If you use `brew cask` you can delete it with a single terminal command: `brew cask zap lunar`

Otherwise, you can delete the following files and folders:
1. ~/Library/Application Support/Lunar
2. ~/Library/Application Support/site.lunarapp.Lunar
3. ~/Library/Preferences/site.lunarapp.Lunar.plist
4. /Applications/Lunar.app
