### ISSUE TITLE
Lunar Diagnostics Report [47B408FF06A1D2CA39D946B6B928C82A9E7571A3CE301E43AA14D3F2F4658A55] [3.2.3]

### ISSUE THREAD

**Issue by remproject** [alin23/Lunar#182]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    *No*

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *Macbook Pro 2015*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *HDMI to HDMI*

- Using an USB Docking Station or Hub:
    *No*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Sync, but checked with other modes which don't work either

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
*no brightness change on my external monitor*

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
