### ISSUE TITLE
Lunar Diagnostics Report [935F31401C0BC77925E941474000FCA3F1291C6635F76F2AE18881EDA028CA84] [3.2.3]

### ISSUE THREAD

**Issue by gabfiocchi** [alin23/Lunar#184]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    *write response here*

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *write response here*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *write response here*

- Using an USB Docking Station or Hub:
    *write yes or no here*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Sync, Location or Manual*

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
*write a short description of what doesn't work as expected*

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
