### ISSUE TITLE
Lunar Diagnostics Report [1C2BCF8784FA77E56FE0D15102DFED2F9C6DC7DF9CA70AF137DB9BEC3F1866E4] [3.2.3]

### ISSUE THREAD

**Issue by benjibra** [alin23/Lunar#188]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    no.

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
   MacBook Pro 2019 13 inch with Touch Bar

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
   2 HDMI to one USB C Adapter

- Using an USB Docking Station or Hub:
    kind of using this one: https://www.amazon.de/gp/product/B07RH9HF4R/ref=ppx_yo_dt_b_asin_title_o05_s00?ie=UTF8&psc=1

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    every mode, Manual was the last I tried
- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
I'm not able to change any value of my to external Displays. Not the brightness and also not the contrast.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
