### ISSUE TITLE
Sync Mode and Manually changes

### ISSUE THREAD

**Issue by ricardopolo** [alin23/Lunar#193]
Hi.

I have my Lunar configured in Sync Mode. However when I use the brightness buttons in the keyboard the external monitor changes independently of the monitor in the Mac.

So, what's the point with the sync mode? The buttons should change the brightness in external and Mac monitor at the same time?

**Comment by alin23** [comment]
If you have Adaptive Brightness enabled in your system, macOS will automatically adjust the brightness of your Macbook display based on the Ambient Light Sensor readings.

In Sync mode, Lunar will detect these changes and sync them automatically to your external monitors so that they are also adjusted based on the ambient light around you.

Given that Lunar looks for any change in brightness, manually changing the internal brightness using the keyboard/TouchBar will also trigger Lunar to sync that change to your external monitors.

![image](https://user-images.githubusercontent.com/3819725/96164975-b1228180-0f24-11eb-9353-139e0f5279c9.png)
![image](https://user-images.githubusercontent.com/3819725/96165130-e3cc7a00-0f24-11eb-95ee-7bdaee7bd226.png)

**Comment by ricardopolo** [comment]
@alin23 I will explain better. 

Lunar allows me to change the brightness of the external monitor, using the keyboard, but I believe this should not be allowed.  When I change the brightness it always should change the brightness of the built in monitor, that later will be reflect in the external monitor.  Right now If I manually change the brightness of the external monitor using the keyboard, it will ignored the bridhness defined by the built monitor.

**Comment by ricardopolo** [comment]
Ok. I'm understanding the issue better.

The sync continues working, but when I use the keyboard brightness keys it modifies the offset used in the algorithm. That's why I feel it stops working. 

![image](https://user-images.githubusercontent.com/1263856/96166632-d8a52a00-0ee3-11eb-8030-226fa85239cb.png)


Any way to stop that behavior and only use sync with the built it monitor?

**Comment by alin23** [comment]
@ricardopolo there are two behaviours here based on where the cursor is placed:

1. When you use the brightness keys in Sync mode while the cursor is on the built-in monitor, it changes the built-in monitor brightness and Lunar syncs that to the external monitor.
2. When the cursor is on one of the external monitors, it adjusts the brightness offset of that monitor to allow for fine tuning the adaptive curve based on the monitor. Some people have more than one external monitor and they prefer this.

I admit that changing an offset isn't that intuitive. I'm working right now on a curve-fitting algorithm where pressing the brightness key will simply adjust the monitor brightness as expected and Lunar will periodically _learn_ how to adapt the brightness based on that.
