### ISSUE TITLE
Lunar Diagnostics Report [NO LOGS] [D7860A342C11710FDF26335A22956397B6D6DAD7AE66E80F563EB2D73D0338FB] [3.2.3]

### ISSUE THREAD

**Issue by delmicio** [alin23/Lunar#197]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    no

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro (Retina, 15-inch, Mid 2015)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI-to-HDMI

- Using an USB Docking Station or Hub:
    yes, but not for the monitor connection

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    tried all of them

# Issue description:
First time trying to use this app, I have the internal monitor with auto-brightness and I wan't to use that for the external monitor

**Comment by RockyMM** [comment]
Which external monitor are you trying to use?

**Comment by delmicio** [comment]
@RockyMM do you mean the brand and model? is a generic one : KTC w2402s

**Comment by RockyMM** [comment]
@delmicio as a hail mary, if you know how to compile a C program, could you try with this utility - https://github.com/kfix/ddcctl

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
