### ISSUE TITLE
Lunar Diagnostics Report [E78FED83302E0CA3D376E740AAD9078FA858829087ECD8FC1C9AD6E136509828] [3.2.3]

### ISSUE THREAD

**Issue by guywiz** [alin23/Lunar#199]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    NO

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Mac Book Pro 2017

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    Thunderbolt adapter to native USB-C

- Using an USB Docking Station or Hub:
    NO

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    MANUAL

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
Changing the different values (brightness, contrats) has no effect whatsoever on my external monitor. Using OS X Catalina 10.15.7

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
