### ISSUE TITLE
Lunar Diagnostics Report [49BD4FE00C548BD8F94220ECE2D93E3B1D6A23ACA3F1B34919287F4742A92C29] [3.2.3]

### ISSUE THREAD

**Issue by Lucasquattro** [alin23/Lunar#200]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
   no, brightness hasn't changed at all

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro 13" i7 2017 (MacBookPro14,2)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    Thunderbolt 3 on an LG 5K2K

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync, Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
Hi there,

I can't manage to make Lunar working via Thunderbolt 3 connection. The monitor does not have other issue with Thunderbolt connection and If I use a dongle and HDMI connection everything is working fine.

Thanks

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
