### ISSUE TITLE
Lunar Diagnostics Report [239EA3CBC93A242418112C169E796E6B176806AE06C82E9A88B34E33C5355FF2] [3.2.3]

### ISSUE THREAD

**Issue by pitosalas** [alin23/Lunar#201]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
yes

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
iMac 

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
hdmi to usb/c (with the lightening bolt)

- Using an USB Docking Station or Hub:
no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
The externall dell monitor seems a little dimmer and when I check the built-in little display for brightness and contrast it seems to drop from 100 to lower (when I plat wutg Lunar) but when I make Lunar tell it to go bright again it doest seem to go all the way

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
