### ISSUE TITLE
Lunar Diagnostics Report [6E577E4104903EAD892A03310BC82C8B4C7CE706476C2F93B50A03FC6433A87E] [3.2.3]

### ISSUE THREAD

**Issue by strefethen** [alin23/Lunar#203]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    *No.*

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *Macbook Pro 2017*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    * I run my MBP in clamshell mode with two external monitors, a Dell, connected via HDMI through a USB-C dongle and an Apple Cinema Display via Thunderbolt to USB-C adapter. Lunar is able to adjust the DELL just fine but the Cinema display doesn't change at all throughout the test.*

- Using an USB Docking Station or Hub:
    *The Dell monitor is connected to the Macbook via an SMK Link hub: https://www.amazon.com/SMK-Link-Mini-Docking-Station-VP6920/dp/B01KA0UR3O/ref=asc_df_B01KA0UR3O*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Location*

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *Yes, this utility works great controlling both monitors in the above setup*

# Issue description:
*The Apple Cinema display doesn't respond to Lunar and the brightness isn't adjusted. Additionally the normal keys to control brightness don't work as long as lunar is running. Press F1 (dimmer) or F2 (brighter) display the indicator but the monitor does not change.*

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
