### ISSUE TITLE
Lunar Diagnostics Report [9DA1AE2E901D102E6A8FDAD9E46DA60C8D4DB5D840A058A8C69F5F3EC4A95ED0] [3.2.3]

### ISSUE THREAD

**Issue by dhruvdutt** [alin23/Lunar#208]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    *No*

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *Macbook Pro 2019 13 inch 1.4 ghz*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *HDMI (Monitor) to USB-C (Laptop)*

- Using an USB Docking Station or Hub:
    *No*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Manual*

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
![image](https://user-images.githubusercontent.com/5961873/99800752-dd03d900-2b5a-11eb-953e-39d504d424f1.png)

# Issue description:
The brightness doesn't change. Tried all modes.

**Comment by dhruvdutt** [comment]
@alin23 Can you please check this?

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
