### ISSUE TITLE
Lunar Diagnostics Report [B247BB7DEA4ACE73C7F319E38DE773ECE1FA72BF1AB597044CA4B003F948E96E] [3.2.3]

### ISSUE THREAD

**Issue by kimstacy** [alin23/Lunar#211]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    Yes

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro 2019 • Big Sur 11.0.1 

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI to USB-C | 2 connections

- Using an USB Docking Station or Hub:
    Yes | 1 connection

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

# Issue description:
A few random issues occurring:

1. The Lunar panel, accessed via menu bar icon hover, goes blank when the brightness or contrast is changed.

![glitch](https://user-images.githubusercontent.com/46656072/100171992-fd9a9e80-2e8c-11eb-9051-c4c07db49971.png)

2. Upon setting a new value, brightness/contrast values will wildly fluctuate and differ from set values.

3. Location Mode and adaptive settings are randomly enabled when on Manual Mode. This cannot be unset. Restarting the app seems to have temporarily fixed it, however, overall behavior is often more erratic than not.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
