### ISSUE TITLE
Lunar Diagnostics Report [D9F94B6D37B732D699395B29FD28E07DEE0208EBC0733C8E3F9105B3395B5338] [3.2.3]

### ISSUE THREAD

**Issue by dariosm** [alin23/Lunar#213]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    Yes

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro 2018 15"

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C-to-USB-C (Thunderbolt)

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Location

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    Not relevant

# Issue description:
The app was working as expected using the `Location` mode, changing the brightness values according to the time for my location. Now for some reason it is stuck at the min bright and contrast values, I can manually change both but the app switches to `Manual` mode when I do that (expected, of course). 
Setting back `Location` mode makes the values back to the min settings. 

Location services are allowed and the correct lat/long is shown in the app.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
