### ISSUE TITLE
Lunar Diagnostics Report [C7D73C4246A2337F377C942408A6B5B5723CE44A61E1E1E79FB0C447D7D93DB7] [3.2.3]

### ISSUE THREAD

**Issue by abfanck** [alin23/Lunar#222]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Mackbook Pro 2018

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI-to-USB-C

- Using an USB Docking Station or Hub:
    Yes

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    No

# Issue description:
Brightness and contrast not changing on the external monitor (LG W2253V).

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
