### ISSUE TITLE
Lunar Diagnostics Report [F04DB39504D7B55176D7419839E917BC53B75A85F45768291F5AD04898123DC7] [3.2.3]

### ISSUE THREAD

**Issue by bdfrye** [alin23/Lunar#223]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
     yes

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Pro 2019

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort, etc.): 
    USB-C-to-USB-C

- Using an USB Docking Station or Hub:
    YES

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
app still switched between Sync Mode and Manual Mode and don't know why

**Comment by alin23** [comment]
Check if **Clamshell Mode Detection** is activated. Deactivate it if you don't need it.
![CleanShot 2020-12-09 at 17 25 15@2x](https://user-images.githubusercontent.com/3819725/101649436-8ac02480-3a43-11eb-95eb-1ec90d6152fd.png)

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
