### ISSUE TITLE
Lunar Diagnostics Report [6349A35171252DCD16C04E34459E4990D407E437CB092BB6A2D4DBA42F346E39] [3.2.3]

### ISSUE THREAD

**Issue by rishit2024** [alin23/Lunar#226]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    no

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Air 2019

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI-to-Thunderbolt 3 (via USB-C hub)

- Using an USB Docking Station or Hub:
    YES

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync, Location, and Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
My HP 27xw doesn't show any changes during the diagnostic. I'm not sure if the monitor even supports display adjustments via the video connection, though.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
