### ISSUE TITLE
Lunar Diagnostics Report [E128382BD51C17C716807C484B70C78822A898D20F66E4B5B24339816D8AC5E0] [3.2.3]

### ISSUE THREAD

**Issue by jain99383** [alin23/Lunar#230]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    Nope

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Pro 2019 13" touchbar

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
   HDMI to USB C

- Using an USB Docking Station or Hub:
    Nope

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual, but the other modes don't work either

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
None of the changes I do in Lunar actually changes anything on my monitor.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
