### ISSUE TITLE
Lunar Diagnostics Report [E26E94F06CE733E17A355B7AF2D949CE58190B24D1D7BEB4F5277A454D94837F] [3.2.3]

### ISSUE THREAD

**Issue by javiercjz** [alin23/Lunar#232]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    Yes

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
MacBook Pro 2019

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
HDMI-to-USB-C

- Using an USB Docking Station or Hub:
no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
Location

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
*write a short description of what doesn't work as expected*

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
