### ISSUE TITLE
Lunar Diagnostics Report [D04411CCF84A325B1DF4C3D8E9B38421A4922B5EEC6D3560FB7F5DE3FC269F67] [3.2.3]

### ISSUE THREAD

**Issue by teasmyth** [alin23/Lunar#233]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    yes

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MBP 2018 15"

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C to US-C

- Using an USB Docking Station or Hub:
    nope

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
Brightness and volume keys on magic keyboard no longer adjust the external monitor's volume/brightness with/without clamshell mode. It used to, but no longer, unfortunately I don't remember what changed. Didn't do any setting change.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
