### ISSUE TITLE
Lunar Diagnostics Report [882E5FA9B246C8F07063FD84615EA700B4F2F56CF619A74182DA609A9DAE8DE8] [3.2.3]

### ISSUE THREAD

**Issue by alliehale** [alin23/Lunar#240]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
   no

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
   Macbook Pro 2019

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
   PN-R496

- Using an USB Docking Station or Hub:
thunderbolt

- Lunar mode used (check it in the top-right corner of the Lunar interface)
   Tried all of them

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
the external monitor is not responsive to the changes I've made in Lunar

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
