### ISSUE TITLE
Lunar Diagnostics Report [6A11CD3B4DF7BCCB8810234D13BD97DBFEAD726D684CB947DF325BD666EC9ADF] [3.2.3]

### ISSUE THREAD

**Issue by aceshig4tw** [alin23/Lunar#242]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
   No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook pro 2020

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C (laptop) to Display Port adapter, DP port on the monitor

- Using an USB Docking Station or Hub:
    No, but an adapter

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sunc

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
Nothing changes on the monitor no matter what setting I try.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
