### ISSUE TITLE
Lunar Diagnostics Report [45C617CA6A5CA38A99FFDEF4EE6778836E4ADC729B2597CCE6FC094D430515D1] [3.2.3]

### ISSUE THREAD

**Issue by freennnn** [alin23/Lunar#243]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    Yes

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbok Pro 2020 16 inch

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C-to-USB-C

- Using an USB Docking Station or Hub:
    USB-C for both display connectivity and laptop charging

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
For example - after adjusting in Quick Pane brightness to 25% (which works) - I open the app, but it still shows Brightness is 90%

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
