### ISSUE TITLE
Lunar Diagnostics Report [ABB0147643CC10FF3ABE421D6F9F3E3B17E0747BA2127F930005CA2EA4DEBC85] [3.2.3]

### ISSUE THREAD

**Issue by kadaan** [alin23/Lunar#245]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Pro 2018

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    Mini Displayport-to-USB-C and USB-A-to-USB-C

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    Yes

```
❯ ./ddcctl -d 1 -b 1
D: CGDisplay AAD0B2F2-ECC3-1294-31FA-22A8B84CFE58 dispID(#69504391) (1920x1200 0°) 94.00 DPI
I: found 1 external display
I: polling EDID for #1 (ID 69504391 => IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG0@1/IOPP/GFX0@0/ATY,Palena@1/AMDFramebufferVIB)
I: got edid.serial: 2A9152A60K0
I: got edid.name: LED Cinema
D: action: b: 1
D: setting VCP control #16 => 1
❯ ./ddcctl -d 1 -b 100
D: CGDisplay AAD0B2F2-ECC3-1294-31FA-22A8B84CFE58 dispID(#69504391) (1920x1200 0°) 94.00 DPI
I: found 1 external display
I: polling EDID for #1 (ID 69504391 => IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG0@1/IOPP/GFX0@0/ATY,Palena@1/AMDFramebufferVIB)
I: got edid.serial: 2A9152A60K0
I: got edid.name: LED Cinema
D: action: b: 100
D: setting VCP control #16 => 100
```

# Issue description:
Lunar indicates that it is changing the external display brightness to match that of the laptop, but no actual brightness change occurs.  ddcctl can change the brightness.

**Comment by kadaan** [comment]
@alin23 Any ideas?

**Comment by alin23** [comment]
For LED Cinema displays, Lunar uses a private CoreDisplay method for changing the brightness, instead of DDC. 
I think that also needs an USB connection between the display and the MacBook because LED Cinema doesn't use Thunderbolt. 

Lunar can also use DDC for these displays but I forgot to include a way to disable the CoreDisplay method. Lunar 4 will be launched soon and will have that.

**Comment by kadaan** [comment]
@alin23 I just started testing the `master` branch today.  It seems to work correctly with my LED Cinema Display.  That said, I do see a number of "No responsive DDC" errors.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
