### ISSUE TITLE
Lunar Diagnostics Report [4766203F37A5ABA1ED4387831607BDAC5D77694695DB3FB2FBBBA10AB11EE5E1] [3.2.3]

### ISSUE THREAD

**Issue by SINCd** [alin23/Lunar#253]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
  no

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
MacMini 2018

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
 DVI-Dual Link to usbc adapter Club3d

- Using an USB Docking Station or Hub:
no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
no

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
In running Diagnostics  it said non responsive DDC

Dell 3007WFP-HC is the monitor i'm trying to use.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
