### ISSUE TITLE
Lunar Diagnostics Report [C1E4ACCB0967946BFD4AD23388EA4F245E2A622C989FA6729CC4962A9C426515] [3.2.3]

### ISSUE THREAD

**Issue by techsin** [alin23/Lunar#254]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    yes

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    yes

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    usb-c to hdmi

- Using an USB Docking Station or Hub:
    yes

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

# Issue description:
pressing keys has no effect but i do see animation of brightness going up and down but it doesn't, nor selecting anything from menu. external monitor has no effect, except when diagnostics ran and it changed it.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
