### ISSUE TITLE
Lunar Diagnostics Report [87A72ABF86C1F0772864211076DCD215D5BEB3D3603C0DCEAAA066BA31AA68D2] [3.2.3]

### ISSUE THREAD

**Issue by jakeharman21** [alin23/Lunar#258]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    YES

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro 2019

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI-to-USB-C

- Using an USB Docking Station or Hub:
    Yes

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Location

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
I have two Dell SE2719H 27" monitors (purchased together) connected to my MacBook (in clamshell mode). The contrast on the left monitor changes with and matches what Lunar says it is set to but the brightness level of the monitor doesn't change with or match what Lunar says it is set at. The right monitor sometimes has the opposite problem but for the most part is working fine with Lunar.

**Comment by alin23** [comment]
Check if you have any setting enabled in your monitor menu that could override the brightness sent by Lunar. 

Also try and see if ddcctl has the same issue. If it does, then it is a problem with either the monitor or the cable/adapter used to connect it.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
