### ISSUE TITLE
Lunar Diagnostics Report [EFB92CB724D910302405F6FB70F23E199D91B48018E75CC78823C7108D10AD07] [3.2.3]

### ISSUE THREAD

**Issue by czkld** [alin23/Lunar#259]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    *yes*

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *iMac 4K late 2015*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *Thunderbolt 2 (minidisplayport) to hdmi*

- Using an USB Docking Station or Hub:
    *no*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Sync*

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
*The brightness doesn't adjust with the brightness of my native iMac display. I mean that the automatic brightness works fine as usual on my iMac display but the external display's brightness stays the same*

**Comment by czkld** [comment]
also, when I use the brightness keys to change the brightness it works fine

**Comment by alin23** [comment]
What external monitor are you using?

**Comment by czkld** [comment]
Dahua  DHL24-F600 (originally meant for CCTV actually)

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
