### ISSUE TITLE
Lunar Bug - Shortcut to change contrast is not working anymore

### ISSUE THREAD

**Issue by karahbit** [alin23/Lunar#261]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro 16" 2019

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    DELL U3219Q

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C to USB-C

- Using an USB Docking Station or Hub:
    no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
Shortcut (control+F1/F2) to change contrast is not working anymore. I use a Magic Keyboard.

**Comment by SanderGit** [comment]
It works on my device, but only if the mouse cursor is on the external display. That might be as designed though.

**Comment by alin23** [comment]
Is it possible that some other app is intercepting the hotkey? I don't see any reason why this specific hotkey would stop working.

**Comment by karahbit** [comment]
Would reinstalling Lunar overwrite/set up all its appropriate hotkeys again?

**Comment by alin23** [comment]
No, macOS stores configuration in a separate folder from the app which doesn't get deleted automatically. You would have to make sure Lunar is not running, and then manually delete `~/Library/Preferences/site.lunarapp.Lunar.plist`
Running Lunar after that will make it start with its default settings and hotkeys.

**Comment by karahbit** [comment]
Thank you for answering so fast. I just did that, and settings were restored, but hotkeys to turn up/down contrast still don't work. On my mac, when I go to System Preferences/Keyboard/Shortcuts/Keyboard I can see the boxes for ctrl+F1 and ctrl+F2 are checked. I tried unchecking them when Lunar is running and still nothing. Any suggestion please?

**Comment by alin23** [comment]
Those _System Preferences_ checkboxes should definitely be unchecked if you want to allow Lunar to receive the hotkey events. Otherwise the system will get the events before Lunar.

#### Try the following:
1. First check if these settings are enabled:
<img width="553" alt="Attachment" src="https://user-images.githubusercontent.com/3819725/108866057-83e58e80-75fc-11eb-902d-75706545c493.png">

2. Then make sure Lunar is in the Input Monitoring list in Security & Privacy (if it is, check and uncheck it for the permission to reapply after the upgrade). Lunar needs these permissions in order to listen globally to the brightness and volume keys.
![40302A88-4F2E-455E-881D-6836F23C78E6](https://user-images.githubusercontent.com/3819725/108866162-9e1f6c80-75fc-11eb-84ef-8d8f5b1cfbb8.png)

3. Make sure this checkbox is **unchecked**:
![Shot_System Preferences_Keyboard_ZAJLQcYN](https://user-images.githubusercontent.com/3819725/108866351-ce670b00-75fc-11eb-87a4-1698998cdb15.png)

Now if you move the cursor to the external monitor that you want to control, you should be able to press F1/F2 for changing brightness and Ctrl-F1/Ctrl-F2 for changing contrast.

If only the brightness works and you are not seeing any contrast changing OSD then something else is receiving the Ctrl-F1/F2 events and you have to find out what that is yourself.

**Comment by karahbit** [comment]
It works now!

In step 3, the checkbox is unchecked. However, in order to turn contrast up/down, instead of ctrl+F1/F2, I have to do ctrl+fn+shift+F1/F2.

Thank you!
