### ISSUE TITLE
Lunar Diagnostics Report [B7D13712B11EF91B4C4195F07F0B011A8E81D4208FFFB243A8E3824319CD6931] [3.2.3]

### ISSUE THREAD

**Issue by ccsbonn** [alin23/Lunar#269]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
yes

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
iMac 27 2020

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
LG Ultrafine 27 via USB-C

- Using an USB Docking Station or Hub:
no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
Lunar crashes randomly and quits without warning or notice

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
