### ISSUE TITLE
Benq EX2780Q not working

### ISSUE THREAD

**Issue by Astraorion** [alin23/Lunar#275]
The App is not working with Benq EX2780Q monitor.

When I click on the shortcut I can see the symbol appearing, but there is no change in the brightness happens.

**Comment by alin23** [comment]
Hi!

Lunar doesn't implement monitor specific logic. It works on all monitors as long as the connection used allows for DDC messages to travel from the GPU to the monitor. 

Try other types of connection if possible (e.g. DisplayPort instead of HDMI) and try to avoid adapters/hubs/docks as these usually block Lunar's messages.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
