### ISSUE TITLE
Lunar Bug: external monitor blackout for 1s when revealing hidden Dock

### ISSUE THREAD

**Issue by delphid** [alin23/Lunar#278]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Pro 2020

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    ViewSonic VX2780-2K-HD Display

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI-to-USB-C

- Using an USB Docking Station or Hub:
    no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
* Dock auto hide enabled
* when mouse reach down to reveal Dock, external monitor blackout for 1s
* only happen when revealing the two Docks in turn (the main screen Dock and the external screen Dock)
* won't happen when consecutively revealing one of the Docks (main/external)

# Lunar Diagnostics Report
[50A5008AB7375AC7D86E75B7F2939B166541108E34794024569C71AD93767256] [3.2.3]

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
