### ISSUE TITLE
Lunar Bug: Crashes when brightness shortcut is used after 100%

### ISSUE THREAD

**Issue by DeeprajPandey** [alin23/Lunar#280]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Pro 2015

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    BenQ GW2480

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI-to-miniDisplayPort (via adapter)

- Using an USB Docking Station or Hub:
    no, however the cable is HDMI-to-HDMI and I am using an HDMI-to-MiniDP adapter.

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    Yes but only on the two miniDP ports but not on HDMI

# Issue description:
When the brightness is at 100% and I use the keyboard shortcut (`Ctrl + F2`) to try and crank the brightness higher, it crashes Lunar.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
