### ISSUE TITLE
Lunar Diagnostics Report [84E4386154776C2A1505C856CC15534A08D99910CC51C3F81C2171802B31CD8F] [3.2.3]

### ISSUE THREAD

**Issue by necenzurat** [alin23/Lunar#281]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    Nope

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Pro 2017

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *write response here*

- Using an USB Docking Station or Hub:
    USB-C to Display Port connected to 2 monitors

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    ????

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    nope

# Issue description:

So, the app only adjusts the the brightness on one monitor, i use 2 identically Dell P2421

**Comment by alin23** [comment]
Are you using an USB-C hub that has two DisplayPort connections? Or are you actually connecting the monitors with two separate USB-C-to-DisplayPort cables?

If you connect both monitors to a single hub, you could probably fix this by connecting one of the monitors directly to the Macbook using a different cable (maybe HDMI)

**Comment by necenzurat** [comment]
2 separarate usb-c to displayport cables

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
