### ISSUE TITLE
Lunar Diagnostics Report [FB22724154CA42E7F74A0BE1ABE1119E8A32B3505935064BE201BD7C9AC2DB3A] [3.2.3]

### ISSUE THREAD

**Issue by salasimo** [alin23/Lunar#287]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
MacBook Pro 13" 4Th 2020

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
   Thunderbolt 3

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
   Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
App doesn't change brightness

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
