### ISSUE TITLE
Lunar Diagnostics Report [A4A556F919A0F5B0D5B95C01CB73224EDBC1C2D9415FB081B83AC8E9BECDF2CC] [3.2.3]

### ISSUE THREAD

**Issue by owisscha** [alin23/Lunar#290]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    Yes!

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MBP2014

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C-to-USB-C 

- Using an USB Docking Station or Hub:
    yes (CallDigit TS3+)

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
'start at login' doesn't work after selecting it in Lunar's options. Had to add it manually in system settings>users and groups

**Comment by alin23** [comment]
Thanks for reporting!
#158 I'm aware of it and will be fixed in Lunar 4

**Comment by owisscha** [comment]
Excellent!

On a different note: any news on the external light sensor? I would love to
see that working.

Op do 11 mrt. 2021 om 14:27 schreef Alin Panaitiu ***@***.***>

**Comment by alin23** [comment]
The software part is ready on the Lunar side. The firmware for the sensor is in testing.

I'm currently testing a prototype using the new $4 Raspberry Pi Pico: 

![image](https://user-images.githubusercontent.com/3819725/110799824-43387700-8284-11eb-97f5-e1c6cfe3cdf1.png)

I don't think I'll be able to ship sensors around the world so I opted for the cheapest and most available components so that everyone can make their own sensors and have Lunar install the firmware and control them.

**Comment by owisscha** [comment]
Awesome, thanks for the update!


Op do 11 mrt. 2021 om 15:14 schreef Alin Panaitiu ***@***.***>
