### ISSUE TITLE
Lunar Diagnostics Report [NO LOGS] [9BA0E2A3D7F06F4C03C8871324DE6A53A9354CAB040353DCD9ED079A9C0280EB] [3.2.3]

### ISSUE THREAD

**Issue by 1709abhishek** [alin23/Lunar#300]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    no
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook air 2019

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI to HDMI

- Using an USB Docking Station or Hub:
    Yes

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
Lunar app not able to control brightness of my monitor

**Comment by alin23** [comment]
Try bypassing the Hub/Dock that you are using. Most likely, that is your problem

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
