### ISSUE TITLE
Lunar Diagnostics Report [5B4FDC8F86A159E66B6654A0231A2292AF0CE368DDCB6855E9D993CF0E83C157] [3.2.3]

### ISSUE THREAD

**Issue by gescarra** [alin23/Lunar#301]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    only 2/3 monitors

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Pro 16" 2019

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    Sabrent TB3 to Dual HDMI 2.0, USB-C to HDMI

- Using an USB Docking Station or Hub:
    Yes, but not for the displays

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    100%. I can read and change brightness on all 3 monitors through ddcctl.

# Issue description:
Description is on a post on #111

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
