### ISSUE TITLE
Lunar Diagnostics Report [https://transfer.sh/GWPjc/lunar.log.enc] [D4A2CA3B8F73728742FC1460CFD4EF01B3015B135DBD89AD30F961870AC18C3A] [3.1.4]

### ISSUE THREAD

**Issue by samtufts** [alin23/Lunar#307]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
no - it turned it off and then back on

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *write response here*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
HDMI to USB

- Using an USB Docking Station or Hub:
  Yes, satechi hub

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
Monitor brightness not changing

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
