### ISSUE TITLE
Lunar Diagnostics Report [ABD587FCDC2191D59F3C7D8F385E0D4A022A5642668A5FC1C8C419913D268488] [3.2.3]

### ISSUE THREAD

**Issue by DovidBaars** [alin23/Lunar#310]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    Only 1/2 monitors

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MBP 2018

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    usb-c to usb-c works, HDMI to usb-c hub does not work

- Using an USB Docking Station or Hub:
    yes

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
*write a short description of what doesn't work as expected*

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
