### ISSUE TITLE
Lunar Diagnostics Report [043EBAAF2ADFF860E92AFD681AE1E4CCA5AB7DBBDC74CCC545814AB310EA3E84] [3.2.3]

### ISSUE THREAD

**Issue by DaniLecx** [alin23/Lunar#311]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    Yes, it went through a few brightness changes.

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Hackintosh (iMac19,1)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI-to-HDMI

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    It doesn't work, I tried with "./ddcctl -d 1 -b 1" and this is the result I get:

```
D: CGDisplay 3D666AB8-B81C-4929-5887-020CC407C9CB dispID(#441002304) (1920x1080 0°) 92.00 DPI
I: found 1 external display
E: Failed to parse WindowServer's preferences! (/Library/Preferences/com.apple.windowserver.plist)
I: polling EDID for #1 (ID 441002304 => (null))
I: got edid.name: VG248
I: got edid.serial: H7LMQS117957
D: action: b: 1
D: setting VCP control #16 => 1
```
I checked and don't have com.apple.windowserver.plist

# Issue description:
Manual mode doesn't work but Lunar diagnostic worked intermittently

**Comment by DaniLecx** [comment]
Got rid of the com.apple.windowserver.plist error when changing resolution and refresh rate in System Preferences > Displays. MacOS created the file itself but ddcctl still doesn't work.
```
danilecx@DaniLecxs-iMac release % ./ddcctl -d 1 -b 1 
D: CGDisplay 3D666AB8-B81C-4929-5887-020CC407C9CB dispID(#441002304) (1920x1080 0°) 92.00 DPI
I: found 1 external display
I: polling EDID for #1 (ID 441002304 => IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/IGPU@2/AppleIntelFramebuffer@0)
I: got edid.name: VG248
I: got edid.serial: H7LMQS117957
D: action: b: 1
D: setting VCP control #16 => 1
```

**Comment by alin23** [comment]
> Lunar diagnostic worked intermittently

That can be caused by slowness in the stack that manages the DDC message sending to the monitor (could be the GPU, could be the system drivers, or even the cable, hard to say)

> `E: Failed to parse WindowServer's preferences! (/Library/Preferences/com.apple.windowserver.plist)`

ddcctl added some additional checks to enable brightness adjustments on multiple monitors of the same model, so it needs more information that macOS usually provides by default. In a Hackintosh it's hard to say what causes that information to be missing.

So if Lunar actually does something from time to time, it means the hardware connection for DDC is somewhat functional. But all you can do for now is experiment with different HDMI cables or ports on your GPU. 

> `D: setting VCP control #16 => 1`

Also if ddcctl says it sent the value but the monitor isn't adjusted, it can mean that the monitor discards that value because of some setting or firmware protection. Try going through the monitor settings to see if there's anything that contains the words _dynamic_ or _adaptive_ that could interfere with DDC.

**Comment by DaniLecx** [comment]
Tried swapping the HDMI cable but it doesn't improve the success rate. Unfortunately I run on my integrated graphics meaning I only have one HDMI port available.
ddcctl does work but very unreliably. I need to spam the command tens of times for the brightness to actually change.

**Comment by alin23** [comment]
If you could test a different monitor (or maybe different Mac device with the current monitor) you could narrow it down to being the GPU's fault or a problem with the monitor.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
