### ISSUE TITLE
Lunar Diagnostics Report [52C2D96A9D79C790700F5E4F78E5FAA576DD69B01EAA499CB64FC0ED186C6887] [3.2.3]

### ISSUE THREAD

**Issue by alonpr** [alin23/Lunar#316]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    yes

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Air 2020

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    miniDisplayPort-to-DisplayPort

- Using an USB Docking Station or Hub:
    no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    yes

# Issue description:
While using the Percentage Hotkeys the contrast value is changing in Lunar but not in the monitor. The brightness is changing as expected both in Lunar and in the monitor.
The contrast range is "unlocked" in Lunar and adjusting the contrast of the monitor works using the contrast up/down hotkeys or from the Lunar app, only the percentage hotkeys don't change the monitor's contrast.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
