### ISSUE TITLE
Lunar Diagnostics Report [3E20EC0D4F41807A768D1C317DA9C56A51D4BE93C8D12C6F6EFD40A489A40C88] [3.2.3]

### ISSUE THREAD

**Issue by jimmy-jose** [alin23/Lunar#318]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
NO

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook pro 2019

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI to USBC

- Using an USB Docking Station or Hub:
   YES

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Tried all 3

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
The brightness  does not change at all

**Comment by alin23** [comment]
Try connecting the monitor without the hub/dock/adapter if you can.

**Comment by jimmy-jose** [comment]
Its a 2019 MacBook pro. It only has usbc input

**Comment by alin23** [comment]
I know, but I don't know your options. 
You could try:
* HDMI-to-USB-C (or preferably, DisplayPort-to-USB-C) cables that have a builtin adapter inside
  * https://amzn.to/3nZVceR
* maybe your monitor has a builtin Thunderbolt connection (probably not, but important to include the option)
* adapters/hubs that support DisplayPort instead of HDMI
* another hub that is known to work with Lunar 
  * I don't currently have a list because the hub is just one of the pieces in a complex Mac/Monitor setup but I can recommend what I use and works
  * https://amzn.to/3teubFm (this supports 4k@30hz or 2k@60hz)

You would have try at least one of these because in your case, I'm 99% sure it's the hub you are using that's blocking the DDC messages that Lunar is using to communicate with your monitor.

**Comment by jimmy-jose** [comment]
Hey thanks for responding quickly. I am from India. I don't know what I spec I should look for before buying the hud. Possible to check if this would work

https://www.amazon.in/BitLoop-MacBook-MicroSD-Thunderbolt-Leather/dp/B07ZX937HP/?_encoding=UTF8&pd_rd_w=tQtXt&pf_rd_p=972ca2f4-f5c6-44c6-92bc-cd08ac3f203c&pf_rd_r=K42CFYCVTPE9MKMZN4XP&pd_rd_r=803743dd-4d96-42fa-973a-a1a3e80c75f5&pd_rd_wg=HPawb&ref_=pd_gw_cr_wsim

**Comment by alin23** [comment]
@jimmy-jose Unfortunately vendors don't mention DDC compatibility in their specs. 

That's why I can only recommend what I've tried. Because the only way to know if a hub is compliant is to actually try it.

But I wouldn't recommend going with this 2-connectors form factor. I have one of those and it's very fragile, all the weight of the cables/accessories is sitting on those small USB-C connectors and it feels like it's going to break any day.
Also, it scratches the Macbook constantly.

I'd say go with a single cable hub like this one: https://www.amazon.in/Novoo-Aluminum-Adapter-MateBook-Chromebook/dp/B075FQY5BN/ref=nav_ya_signin?dchild=1&keywords=macbook+hub&qid=1620744199&s=electronics&sr=1-3&

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
