### ISSUE TITLE
Lunar Diagnostics Report [7C64DFF20E11EB056B34D91FBB98DF0A2F053A3568023B11CF68BC5B75D218E5] [3.2.3]

### ISSUE THREAD

**Issue by CyrosX** [alin23/Lunar#320]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
Macbook Pro late 2013 - Big Sur 

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
DVI-DP

- Using an USB Docking Station or Hub:
No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
Manual (none works)

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
No

# Issue description:
Does not seem to work. Where can I find the logs?

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
