### ISSUE TITLE
Lunar Diagnostics Report [029F7477B6854DDB142A72FC50C82D1A0A3161BF23147A8E371D656829FD1E3B] [3.2.3]

### ISSUE THREAD

**Issue by koetsuji** [alin23/Lunar#321]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    Yes

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Pro 2016 13" MacOS 10.15.7 Catalina

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    HDMI to MINIX multi-dongle to USB-C (http://minix.com.hk/products/neo-c-mini)

- Using an USB Docking Station or Hub:
    Yes MINIX

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sync Mode

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
When I open or close an application, I get blue flashs for 1 second. All the monitor screen turns blue and everything lags. When I turn off Lunar I don't have this problem. I can send you a video if needed.

**Comment by alin23** [comment]
Try disabling the **Read monitor brightness periodically** setting if you enabled it. 
If that doesn't help try disabling **Smooth transition**

This is a hardware problem. Lunar can't fix this, it's your monitor that has this response to DDC programmed inside its firmware.

**Comment by koetsuji** [comment]
Thanks, I have them both disabled. Nothing changes. Guess there is nothing
to do for it for now.

Cordialement / Best regards,
Agah Celen

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
