### ISSUE TITLE
Lunar Diagnostics Report [428712B95A0C22EB28F769A053CC17FE8EBC0DB0FA66299FC3586DC9F98F91BA] [3.2.3]

### ISSUE THREAD

**Issue by jeremypng99** [alin23/Lunar#323]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    no

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro 2017

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    hdmi to hdmi

- Using an USB Docking Station or Hub:
    yes

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
unable to change the brightness of the external display totally

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
