### ISSUE TITLE
Lunar Diagnostics Report [A773D8ADE5D64B5FB335C938E38C71F9AFAAB2281159A53C870B16E12D3C5405] [3.2.3]

### ISSUE THREAD

**Issue by kevinyuan** [alin23/Lunar#324]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    *Yes*

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *MacBook Air (Retina, 13-inch, 2020)*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *AOC Q2790R3*

- Using an USB Docking Station or Hub:
    *No*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Manual*

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:

Lunar doesn't start at OSX login, even "Start at login" is checked.

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
