### ISSUE TITLE
Lunar Diagnostics Report [NO LOGS] [55B01AD9A25A4FAC07793D6BE3A147D5E438619020AC270009C0941F0D4EB717] [3.2.3]

### ISSUE THREAD

**Issue by iChristosK** [alin23/Lunar#327]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    *No*

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *Macbook 2016*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *USB-C to HDMI*

- Using an USB Docking Station or Hub:
    *No*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Sync

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
*Changing brightness on my external display doesn't change when I do it manually with Lunar*

**Comment by alin23** [comment]
Possible fix in **Lunar 4**.

You can download it from the official website: https://lunar.fyi

If the issue is not fixed, click on **Open Lunar Diagnostics** from the Lunar menu, press keys when prompted, and after the diagnostics process shows it has finished, fill in your name and email and click on **Send Diagnostics**.

*Note: Lunar 3 is not supported anymore and I won't be responding to issues coming from that version*
