### ISSUE TITLE
Lunar doesn't work with monitor connected via Hyperdrive Gen 2 dock - Diagnostics Report [CAC6A3E72735AE9F23955172C0BA24333741D1C5DEC223EE2C19C6690C18139E] [3.2.3]

### ISSUE THREAD

**Issue by vishusingh** [alin23/Lunar#328]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    No, I should add that this problem started occurring when I switched from the external display connected directly via usb-c to DisplayPort dongle to the display port on my dock (Hyper Drive Gen2).

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro 2019 13"

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    DisplayPort to DisplayPort (Hyper Drive Gen 2 dock connected to the MacBook via Thunderbolt)

- Using an USB Docking Station or Hub:
    Yes

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
I get a 'Failed to send DDC command!' error -
![image](https://user-images.githubusercontent.com/11193457/119671448-0ec36880-be3a-11eb-8c5d-ce5d6c67476d.png)

# Issue description:
Previously, I had my monitor connected via a Display to USB-C dongle and Lunar was working fine for me.

I've now got a Hyperdrive Gen 2 docking station and connected my monitor to its DisplayPort, the dock is connected via a thunderbolt cable to my MacBook Pro '19.

Lunar has since stopped working, as in, it's unable to change the  brightness/contrast for my monitor and I get this error on the UI --> 'Non responsive DDC'

**Comment by rafaelpirolla** [comment]
Is there anything we could do with the dock itself? It's expensive. :|

**Comment by alin23** [comment]
You could do some troubleshooting to make sure if the issue is with the dock or something else. 

Try connecting the monitor to each video port (DP, HDMI1, HDMI2) and try Lunar 4 diagnostics on each connection and see if any of them works. 

![image](https://user-images.githubusercontent.com/3819725/122016663-ea6c0380-cdc9-11eb-89b0-f7ab79ba0eda.jpeg)

To use diagnostics, click on Open Lunar Diagnostics in the Lunar menu, press keyboard keys when prompted by the text, and after finishing the process click on the Send Diagnostics button.

Make sure you are using Lunar 4, here's a build with a lot more fixes than what is on the official website: https://static.alinpanaitiu.com/Lunar8.zip

This will be released as Lunar 4.1.0 this week if testing goes well.
