### ISSUE TITLE
Lunar Bug - issues/suggestions about setting up Raspberry Pi 

### ISSUE THREAD

**Issue by tjluoma** [alin23/Lunar#345]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
Mac mini (M1, 2020)
Macmini9,1

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
DELL U2718Q

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
Mac mini connects to CalDigit dock, dock connects via Mini Display Port (on dock) to Display Port (monitor)

- Using an USB Docking Station or Hub:
Thunderbolt,  technically, I think… CalDigit TS3+

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Sync, Location, Sensor or Manual*

manual 

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. **Make sure to not click anywhere in the window**
> 3. Press keyboard keys when prompted by the text
> 4. After finishing the process click on the **Send Diagnostics** button.

no (not applicable)

# Issue description:

1. There's no information that I could find on the website on how to set up the Raspberry Pi connection. I looked all through the app as well. It didn't occur to me that it would be on the menu bar dropdown list.

2. I set up a static IP for my Raspberry Pi to make sure that Lunar would always be able to find it at the same place where it was when I did the initial setup. But at the end of the installation process, it said: `NOTE: The hostname has been changed from 192.168.7.197 to rpi-ddc-76a0.local to avoid name clashes`. That's not a hostname I wanted to use, and I was not very happy that Lunar decided to change it on its own.

3. Now that it is set up, I have no idea where to go to change any of the settings, if that's something that I need to in the future. I don't want to go through the whole installation process again, but what if I just need to change the password that Lunar uses via SSH? This really needs a UI if it is set up.

4. After I changed the hostname and rebooted the Raspberry Pi, Lunar silently switched from "Network Control" to "Software Control". If Lunar has been set up for Network Control but can't access the Raspberry Pi, Lunar ought to inform the user of that.  Once I quit and restarted the Lunar app, it went back to Network Control.

**Comment by alin23** [comment]
1. Yes, I should write a more detailed tutorial on how to install the server, it's not discoverable enough
2. The DDC server used mDNS/Bonjour/zeroconf to advertise itself over the local network. There's no need for a static IP.  Not everyone knowS how to set up a static IP. 
3. Those settings that you inputted in the installer window are not stored anywhere. Lunar  doesn't use SSH anymore after the installation is done. It's just a one time thing. 
4. Lunar actually asks you if you want to switch to software control if the pi becomes unresponsive. But if the server on the pi quits gracefully, it advertises that as a service removal on the network and Lunar sees that and considers it a voluntary action (something that you maybe chose to do because you don't want network control anymore). I could ask the user in that car too but I don't want the prompts to become annoying.

**Comment by alin23** [comment]
You are free to change the hostname to something else as long as you know it is unique in the local network. Just do it using the raspi-config utility to make sure it persists:

`raspi-config nonint do_hostname your-hostname`

And then reboot the Pi. 

The server should start advertising itself using the new hostname.
