### ISSUE TITLE
Better onboarding experience

### ISSUE THREAD

**Issue by jjeising** [alin23/Lunar#368]
### Name of the feature

The onboarding experience of Lunar should be better.

### What problem does this feature solve?

Lunar changes screen settings on first start, without any user interaction, while multiple permission dialogs, trial dialog and others are shown. This is a really bad experience, as the displays might get dark or bright, contrast settings which the user previously set might change.

### How should the feature work

Maybe Lunar should not start in Sync Mode (?), but ask for settings first and have prominently "Start Sync Mode now" button. Or there could be an onboarding assistant, which guides through the different settings screens, starting in manual mode and choosing the mode last.

**Comment by alin23** [comment]
Thanks for the feedback!

Most people install Lunar specifically for the sync mode so I'd like to keep that as the default. It's my personal choice. 

The permission dialog can't be shown at a later time, otherwise you wouldn't be able to use your brightness/volume keys to control the monitor. 

The trial dialog is also something that I want users to see from the first time so that they don't get confused after 14 days when Lunar loses the Pro features and think it's a bug. 

I know it doesn't feel like a good experience to you but some information needs to be conveyed from the first launch, otherwise I'll get buried in support emails for unnecessary things.

**Comment by alin23** [comment]
I thought about this some more and I think you're right. Lunar should have a better onboarding experience. 

I'll try to come up with some ideas and I'll post them here, in the hope that you can bring some feedback from an experienced user perspective. 

Sorry if I sounded a bit harsh in my last comment. This onboarding thing is something devs can't really understand as much as new users do because we already know so much of how the app works that everything seems obvious in our eyes.

**Comment by alin23** [comment]
Added an onboarding process in Lunar 5
