### ISSUE TITLE
Please stop updating Lunar every other day

### ISSUE THREAD

**Issue by sn0wyfall** [alin23/Lunar#374]
I really like Lunar, but please stop updating it every other day. It's basically become nagware at this rate, the way it wants to update for every single little feature.

**Comment by alin23** [comment]
There has been no new feature added in the last 3 weeks. The updates are only bug fixes.

They are so frequent because I wake up every day with a ton of support emails from people that are so annoyed by something that doesn't work properly for them that they ask for a refund.

So I'd rather get that fixed as soon as I can because if I don't, the next day there will be 10 more users that have the same problem and ask for the same thing and so on.

You can tell Lunar to check for updates less often by running one of the following commands in a terminal:

### Check for updates every 3 days
```shell
defaults write fyi.lunar.Lunar SUScheduledCheckInterval 259200
```

### Check for updates every week
```shell
defaults write fyi.lunar.Lunar SUScheduledCheckInterval 604800
```

I would have added this setting in the UI today but this would need yet another update which would probably annoy you even more.

**Comment by alin23** [comment]
@sn0wyfall you can now choose weekly updates from the UI in 4.3.0:

![Shot_Lunar_Settings_rJ0iKWfX](https://user-images.githubusercontent.com/3819725/123910608-60a06680-d983-11eb-8daa-3fb95847b3a0.png)

**Comment by sn0wyfall** [comment]
@alin23 Thank you, I appreciate it :) My apologies if I originally sounded snarky

**Comment by alin23** [comment]
No worries! To avoid any confusion, I had to take down 4.3.0 because of some weird bugs so the above update interval toggle will not be available until the next update.

The next update will probably be 4.5.0 because DDC support for M1 is finally coming and it's a major update. I hope to release it in the next few days
