### ISSUE TITLE
Lunar Bug

### ISSUE THREAD

**Issue by dtliao0303** [alin23/Lunar#378]
# Issue details
- Mac device where Lunar is installed:
    *Mac Mini M1*

- Monitor model:
    *MSI PS341WU*

- Monitor connection to the Mac device:
    *Thunderbolt-3, USB-C-to-USB-C*

- Using an USB Docking Station or Hub:
    *No*

- Lunar version:
    *v4.4.0-beta3*

- Lunar mode used:
    *Manual*

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. **Make sure to not click anywhere in the window**
> 3. Press keyboard keys when prompted by the text
> 4. After finishing the process click on the **Send Diagnostics** button.

    *Yes, send it to myself but never received it, where else can I get a log?*
    *But this issue is done with mouse clicks and no pressing keyboard keys.*

# Issue description:
*1.) Menu Bar Popup shows extra ghost monitor. "Click to remove" will remove for a second and then it pops right back up.*
*2.) Discovered ghost monitor is from HDMI port, previously connected, but NOT connected anymore.*
*2-1.) Discovered by reconnect HDMI cable will make the ghost monitor "active" and does not have "Click to remove" option*
*3.) By connecting & disconnecting HDMI cable. "Click to remove" work and ghost monitor stay removed. But after system restart it shows back up again and cannot be removed like 1.)*

*Note: only 1 monitor is connected*

![IMG_0104](https://user-images.githubusercontent.com/4142786/124381274-34bf1100-dcf4-11eb-8c95-7824550a668f.jpg)

https://user-images.githubusercontent.com/4142786/124381278-38529800-dcf4-11eb-9150-10a3c83a6555.mov

**Comment by alin23** [comment]
Hi @dtliao0303 !

There are a few misunderstandings here.

1. Diagnostics are sent to me through Sentry, not to yourself. The email and name are there so I can reach back to you about the problem.
2. When you start the diagnostics process, the text in the middle of the window will ask you to press any key (or the Enter key in some cases) to continue the process. That's what I meant by _press keys when asked_. 
  - You have to make sure that you're not focusing any other input otherwise the keys won't be registered and the process won't continue. 
3. The _ghost_ monitor is completely normal. 
  - The system assigns different ids for monitors based on what port they're connected on. But Lunar can't know that you're connecting the same monitor on different ports from time to time. 
  - For an app, the monitor connected on HDMI looks completely different from the same monitor connected to USB-C. This is a limitation of the system. 
  - Lunar keeps the disconnected monitors around to store their setting so that the next time you reconnect them, their saved settings are restored. 
  - Sometimes macOS can assign a different id even on the same port so Lunar will see that as a new monitor different from all the other that were stored until now. Again, nothing we can do to fix this.

**Comment by dtliao0303** [comment]
@alin23 That's unfortunate, but thank you for the clarification. It's a great app nonetheless!
