### ISSUE TITLE
Lunar Feature - Sensor build Instructions

### ISSUE THREAD

**Issue by andrewcrook** [alin23/Lunar#382]
When will the Sensor parts list, diagram, instructions and code be available?

PS I am the person who sent you the GitHub/Gist links regarding DDC M1 support the other day.

**Comment by alin23** [comment]
@andrewcrook still working on it, I can't say for sure when it will be ready.

I had to put it on hold because of the DDC on M1 work and fixing a lot of bugs in isolated setups.

Do you have any specific MCU at hand? 
Sensor Mode over serial is already very well implemented in Lunar through Pi Pico and any I2C sensor from this list: 

* VEML7700
* TSL2591
* TSL2561
* TCS34725
* VCNL4040

If you already have a Pi Pico and one of the above sensors, you could simply connect the following:
1. SCL of the sensor to GP19
2. SDA of the sensor to GP18

![Pico-R3-Pinout](https://user-images.githubusercontent.com/3819725/124911861-ebbdd400-dff5-11eb-97f2-1bdaddf26a81.png)

And then connect the Pico through USB to the Mac where Lunar is running.

Lunar should detect the Pico and ask if you want to set it up as a light sensor.

The wireless sensor instructions still need some work, but I'll post both solutions when they're ready.

**Comment by alin23** [comment]
@andrewcrook The tutorial and firmware for the DIY Wireless sensor is done.

Make sure to update to `v4.6.2` by clicking on `Check for Updates` in the Lunar menu.

And check out the tutorial here: https://lunar.fyi/sensor

**Comment by andrewcrook** [comment]
@alin23  Super thank you, I’ll have to order the parts. See if I can find some suitable housing

**Comment by alin23** [comment]
I gave up on trying to find housings for electronic projects 😅

Nowadays I just drive a small screw through the board holes into a thin piece of wood, like seen here:
![Shot_Sketch_Pro Display XDR Mockup sketch_i1IURBuc](https://user-images.githubusercontent.com/3819725/125958006-fe40febd-71b7-4659-9e17-0fa8d91b16b7.png)

Works well to give the board a solid base and looks good enough.
