### ISSUE TITLE
Mode resets to Manual

### ISSUE THREAD

**Issue by igRo** [alin23/Lunar#388]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    MacBook Pro 2019

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Dell P2421DC

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C-to-USB-C

- Using an USB Docking Station or Hub:
    none

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Auto

- Tried Lunar Diagnostics?
    yes (DELL P2421DC [F8F184DD-001B-6D62-0125-8C44E56B9CD5])

# Issue description:
Mode sometimes resets from Auto to Manual when I connect the monitor. I use two different monitors (at home and in the office) and sometimes I notice that the mode is reset from Auto (or Location) to Manual, it seems to happen even during the day. Didn't manage to reproduce it right now by connecting/disconnecting and opening/closing the lid.

**Comment by alin23** [comment]
If you have Clamshell Mode detection enabled in Advanced settings and you close the lid, Lunar will go to manual mode until you open the lid again. 

Disable Clamshell Detection if you don't want this behavior:

![image](https://user-images.githubusercontent.com/3819725/126012215-7d60ed8c-280f-4874-909e-207df8f4efb7.jpeg)

**Comment by igRo** [comment]
Oh, failed to reproduce the issue by closing the lid, but if there is any noticeable delay, then that could certainly be the cause.

So maybe in this case it would be better to toggle between Sync and Location modes instead?

**Comment by alin23** [comment]
Yes, that's what Auto Mode does by default already.

If you have the lid open, Sync Mode is available and will be chosen. When the lid is closed, Sync Mode is not available anymore because the light sensor is covered, so Auto Mode will choose the next mode which is Location.

Clamshell Detection is when you don't want to fallback to Location, but straight to Manual. Location mode is not for everyone, you need to be in a room with lots of natural light for it to make sense.
