### ISSUE TITLE
Lunar lagging when scrolling through preferences UI, CPU usage spike

### ISSUE THREAD

**Issue by fancymans** [alin23/Lunar#389]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    M1 Mac mini

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    LG 38WN95CW (Hardware Control)
    LG 32UL950 (Software Control)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    LG 38WN95CW - Thunderbolt to Thunderbolt
    LG 32UL950 - HDMI to HDMI

- Using an USB Docking Station or Hub:
    Yes for Thunderbolt (CalDigit TS3+)
    No for HDMI

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. **Make sure to not click anywhere in the window**
> 3. Press keyboard keys when prompted by the text
> 4. After finishing the process click on the **Send Diagnostics** button.

    No

# Issue description:
After updating to latest release, Lunar started behaving slower than before. When I swipe between each page of the preferences window, it will stutter and lag. Observed to be worse on Auto mode vs. Manual but both modes are noticeably laggy. Swiping through the settings show % CPU increase up to 60% and higher. Changing brightness with hotkeys still seem to work fine without slow behavior. Performance hit might be isolated to navigating the preferences only.

![Screenshot 2021-07-19 at 01 35 56](https://user-images.githubusercontent.com/7216440/126130038-dc0ee390-71e0-453a-85ec-e9e8583715dd.gif)
![Screenshot 2021-07-19 at 01 38 01 2](https://user-images.githubusercontent.com/7216440/126130756-a9d8c386-5c0e-4c0b-8bde-db83d892a6f4.gif)

**Comment by alin23** [comment]
The performance hit is caused by the curve graph being recomputed on every page change. 

I'll see if I can improve this by caching the last computed values.

**Comment by alin23** [comment]
@fancymans can you check if this build fixes the lag for you: https://static.lunar.fyi/Lunar-4.6.4-beta1.zip

Here is a video on how it looks on my end:

https://user-images.githubusercontent.com/3819725/126151253-c6dfe093-2502-4ddd-9e4d-344ac6b55bfa.mp4

As you can see, there is still **some jitter when swiping** with the trackpad, but the transition is **smooth when using the arrow keys** and buttons.

That means the swipe jitter is caused by the `NSPageController` view from the macOS UI framework, and I don't think I can do much about it.

I removed all the redundant computation to keep the CPU usage low. The remaining CPU usage is caused by the system which is rendering the UI as it is.

**Comment by fancymans** [comment]
Yup fixed in the beta build! Significantly better and more smooth. 👍🏼

**Comment by alin23** [comment]
Awesome! I'll release the fix in v4.6.5 soon
