### ISSUE TITLE
Error updating to v4.7.0

### ISSUE THREAD

**Issue by timtraversy** [alin23/Lunar#395]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    MacBook Pro 2019

# Issue description:
When updating to v4.7.0, the update dialog displays the error `An error occurred while running the updater.`

In the Console logs, I get
```
Lunar	Error: An error occurred while running the updater. Please try again later. The remote port connection was invalidated from the updater. For additional details, please check Console logs for Autoupdate. If your application is sandboxed, please also ensure Installer Connection & Status entitlements are correctly set up: https://sparkle-project.org/documentation/sandboxing/ (URL (null))
Lunar	Error: Update validation was a failure (null) (URL (null))
Lunar	Error: The update has a public (Ed)DSA key, but the public key shipped with the update doesn't match the signature. To prevent future problems, the update will be rejected. (null) (URL (null))
```

Seems like it could be a signature issue?

**Comment by alin23** [comment]
Oh, it's because you weren't on 4.6.5 already. I switched to only using EdDSA signatures because DSA was deprecated (less secure).

I'll try to add the DSA signature as well until the for the next few weeks until everyone is up to date. Until then, you can download 4.7.0 manually from https://lunar.fyi/download/latest

**Comment by timtraversy** [comment]
Thanks! Sounds like this is solved.
