### ISSUE TITLE
Feature request: put internal display to sleep with lid open

### ISSUE THREAD

**Issue by lijunkang12** [alin23/Lunar#40]
Hi there!

First of all, thank you so much for writing this app. It works like a charm! And the UI is simple but elegant.

I have a little feature request, maybe not so relevant with your app but I think many people working with an external display would love to have it: the possibility to put internal display to sleep with lid open when connecting to an external display. This feature will be useful for those who don't use the screen of their mac but need to keep the lid open for heat reason or they need to use the keyboard and trackpad of the mac. It is not without interest to do so especially because putting the display of the mac to sleep reduces the workload of the GPU, which is also the reason why it is not equivalent to adjusting the brightness of a mac to zero.

However, such a simple feature is not implemented by the macOS itself. And most frequent approaches suggested on the internet consist of using some command line commands or a physical hack using some magnets. If you happen to know how to resolve this problem, it would surely be wonderful to include it as a new feature of your app.

Thanks again for your app and your time for considering my request.

Cheers!

**Comment by alin23** [comment]
Hi @lijunkang12 !

Thanks for the kind words! 

The feature would be a good addition to Lunar, but unfortunately this is mostly controlled by hardware or kernel flags.

I'll write down some of the workarounds I've seen and tried and their drawbacks:
1. Setting the internal brightness to 0. This is the cleanest and easiest to implement in Lunar but has two big drawbacks:
    1. The GPU is still working to draw things on the internal screen, you just don't see it anymore.
    2. Windows and dialogs can be drawn on the internal screen and you will have no idea what is happening because you won't be able to see them. Activating screen mirroring helps with this but messes up with the external monitor resolution
2. `sudo nvram boot-args="niog=1"` This is impossible to implement in an app. It has to be ran manually with SIP disabled. Also it seems to be the only thing that actually works as expected so I would recommend you to try this.
3. Magnets placed on the reed switches. This works exactly as if you had closed the lid, because that's how the Macbook detects a closed lid, through [reed switches](https://youtu.be/zTbv5szQNoA?t=60)

There's no API that Lunar can use to just disable the internal display. If Apple doesn't implement this functionality, then we can only resort to the above workarounds.

**Comment by lijunkang12** [comment]
I see. Thank you anyway for your kind reply!
