### ISSUE TITLE
Controlling only the built-in display in Manual mode

### ISSUE THREAD

**Issue by aaronraimist** [alin23/Lunar#408]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    MacBook Air 2020 M1 with macOS 11.5.2

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    LG 27BK85U-W

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C-to-USB-C

- Using an USB Docking Station or Hub:
    Yes

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. **Make sure to not click anywhere in the window**
> 3. Press keyboard keys when prompted by the text
> 4. After finishing the process click on the **Send Diagnostics** button.

    No

# Issue description:
After updating from 4.8.1 to 4.8.5 my manual mode started working differently. Rather than letting me adjust each monitor individually Lunar seems to be using the Sync mode because when I adjust my built in display it also adjusts the external display. I tried upgrading from 4.8.1 to 4.8.2 and that experiences the same problem so I believe it regressed in 4.8.2.

**Comment by alin23** [comment]
This is actually a fix that changed the behavior. 

In Sync mode, Lunar is supposed to only control the built-in display when the brightness keys are pressed without any modifiers, because the rest of the monitors will be adjusted by the Sync algorithm in less than a second (or more depending on your polling interval)

In previous versions there was a bug that caused this behavior to not happen, so you got used to the buggy behavior. 

The default way to control the external display in Sync mode is Ctrl-Brightness, because you shouldn't need to do that too often, only when the Sync algorithm doesn't get the brightness right and you need to fine tune the curve.

**Comment by alin23** [comment]
Actually you seem to be talking about Manual mode using Sync mode somehow? 

I would say that's not possible, 4.8.2 has been launched for more than a month and there wasn't a single report of that happening.

What keys are you pressing when changing brightness for built-in?

And can you check that the **Include built-in display** is unchecked in the [Hotkeys page](https://app.lunar.fyi/hotkeys)?

**Comment by aaronraimist** [comment]
When I press the brightness keys with no modifier, both displays change brightness.

When I press Control+Brightness Key then only the external display changes (correct behavior).

These are my Hotkeys settings. That option is unchecked.
<img width="1062" alt="Screen Shot 2021-09-12 at 11 17 20" src="https://user-images.githubusercontent.com/5855073/132995061-c9e66f97-50a0-4f86-9a7e-4baf6bb2a0cc.png">

**Comment by aaronraimist** [comment]
Oh hmm is the Send keys to all monitors a new feature?

**Comment by aaronraimist** [comment]
Okay I think I see what happened. I did not have Send keys to all monitors enabled on 4.8.1 (somehow got enabled) and I guess the feature where it uses the cursor wasn't working so I had always just used brightness key alone to control built in and Ctrl+Brightness to control external.

I will try for a while with the new (to me at least) cursor behavior though I'm not sure if I actually want that.

**Comment by alin23** [comment]
The **Send keys to all monitors** has been around since the first versions of Lunar 4 so it's not new. 

But _all monitors_ didn't also include the builtin display in <v4.8.2 versions. That also got fixed with the other Sync mode bug.

So I see now that what I've done is I've taken away the case where you want to:
1. Use Manual mode
2. Adjust only the built-in display no matter where the cursor is

I'm not sure exactly how to fix this without breaking the other cases.

**Comment by alin23** [comment]
@aaronraimist can you try [this beta](https://static.lunar.fyi/Lunar-4.8.6-beta1.zip) and check if you the new hotkey behaviour suits your needs? 

You might want the following settings:

![Shot_Lunar_Settings_gdz81fyg](https://user-images.githubusercontent.com/3819725/133335016-53c96da9-052a-45c6-ba9f-7711b4543f68.png)

**Comment by aaronraimist** [comment]
Yep that works well. Thank you!
