### ISSUE TITLE
Increase max brightness for 2021 Macbook Pros

### ISSUE THREAD

**Issue by andrewdotcallahan** [alin23/Lunar#417]
### Name of the feature

Push the brightness of the new XDR display macbook pros past the default allowance of 500 nits.

### What problem does this feature solve?

Principally, this would be useful for working outdoors in sunlight.

### How should the feature work

[Apple advertises the new Mini-LED MacBook Pro 14 with a peak brightness of up to 1600 nits and a sustained brightness of 1000 nits, but these values seem to be limited to HDR contents. Standard SDR contents are limited to 500 nits, which is comparable to the current MacBook Pro 13](https://www.notebookcheck.net/The-new-MacBook-Pro-14-only-manages-500-nits-with-SDR-contents.575327.0.html).

I'm wondering if it's possible to hack around this somehow.

### Visual description

This could be presented in Lunar as a "brightness boost" toggle.

**Comment by sagz** [comment]
+1 to this suggestion. I came to the issues page just to post the exact same request! 

I want to be able to push the display to the advertised "sustained 1000 nits" every once in a while for short durations when doing a video call outdoors.

Is it possible to simulate HDR content as an overlay across the screen? It's a dirtier hack for sure, but might work (there are [reports](https://youtu.be/FmH1HgDhrWI?t=520) that with HDR windows, MacOS makes only those windows in HDR while other SDR windows stay in lower brightness)

Another hack I wonder is if one could create a 'custom preset' from such a list:
<img width="554" alt="image" src="https://user-images.githubusercontent.com/964843/139786081-a8843a2c-6ba7-41db-8e2e-57322312fc52.png">

**Comment by alin23** [comment]
Over the past week I tried to find a way to get past the 500 nits limit but unfortunately I couldn't find any method.

I've shared my findings in this blog post: https://alinpanaitiu.com/blog/over-500nits-failed/

**Comment by sagz** [comment]
Thanks a lot for writing and sharing that @alin23 ! It was such a fun read :) Looking forward to what's more to come (including @waydabber's proposal of a transparent Metal layer to switch modes + tonemapping)

https://github.com/waydabber/BetterDummy/issues/163#issuecomment-1014816057

**Comment by alin23** [comment]
@sagz @andrewdotcallahan @janvotava @beaugunderson @rokcarl @nitsujri @panckreous I managed to get something working on raising this 500nits limit.

Is anyone interested in testing this? Here's the beta with the changes: https://files.lunar.fyi/Lunar-5.4.3-beta10.zip

The feature needs a Pro license, so here's a 7-day valid license for testing: `484194B6-5F12AECF-05F582BB-45255B27-053882AA`

## What to test

### Enable XDR brightness

This can be done either through the `SDR | XDR` toggle in the menu bar or through the `Enable XDR Brightness` button in the Preferences window.

![Shot-Lunar-23-02](https://user-images.githubusercontent.com/3819725/158261217-6acb0331-ad80-4aec-a1ed-5bc92f2d204f.png)

### Adjust XDR brightness using the brightness keys

The over-500nits brightness has a separate custom OSD because the system is still capped at 500nits on 100% brightness. 

Currently, the only way to adjust this brightness is through keyboard keys. I'm still thinking about how to add a slider for this.

![Shot-CleanShot-23-32](https://user-images.githubusercontent.com/3819725/158265001-aa84c114-8711-4128-a5a3-9212845f76c9.png)


### Check white content on XDR

This video is a good way to see how white over 500nits looks: [hdr-test-pattern](https://files.alinpanaitiu.com/hdr-test-pattern.webm). Launch in Safari and quit f.lux or other Gamma altering apps to make sure it has the wanted effect.

Check if other white content on the screen matches the HDR white in the video when XDR brightness is enabled in Lunar.

### Notice glitches

When XDR mode is enabled, the system becomes glitchy. You may see flashes, broken animations, and an overall UI latency.

This is not a Lunar problem, any HDR content has the same effect. Report if any part of this experience becomes so annoying that you would stop using this feature.

## Bonus: sub-zero dimming

This is another feature, inspired by something @waydabber introduced in MonitorControl.

To enable it, use the keyboard to lower the brightness below 0. Another brightness OSD will appear to let you know sub-zero dimming is applied.

This should work on all monitors, not just on the MacBook XDR display.

![Shot-CleanShot-23-31](https://user-images.githubusercontent.com/3819725/158265196-519fbcf6-d509-4e8d-8af8-935b828c2e5d.png)

**Comment by sagz** [comment]
Yes! testing this in a few hours!

**Comment by waydabber** [comment]
Hey @alin23 - Simply elevating CGGammaValue gamma table max levels above 1 will push XDR display brightness into the EDR/HDR range or is there anything else? I'd like to implement this one into MonitorControl as everything is there already and as you say we already utilize a combined gamma/hardware dimming technique (which you just nicely copied finally ;)) but only on the dimming side, not the brightening. Unfortunately I don't have an MBP so I can't experiment - my trusty old MBA produces a perceived brightening by elevating max values (but this of course does not affect the backlighting so its just a skewed gamma table) - on an Apple mini-led display like the XDR does it indeed (?) make the mini-leds shine brighter?

**Comment by alin23** [comment]
@waydabber no, raising the Gamma value won't have any effect. It involves some internal Skylight and CoreBrightness APIs. 

I'd like to keep this proprietary for now. I've worked way too many 12-hour days to get to the bottom of this and get an edge over the competition.

**Comment by waydabber** [comment]
Oh, I see. So what's interesting is that gamma values go beyond 1 on my MBA when enabling the option, but it's simply resulting in an "overdrive" effect. Is it only because it is a beta and probably the functionality is not limited yet to the proper displays at the moment and I should not be able to activate this on a non-XDR display? Anyway, increasing gamma might be part of how this works but obviously you need to "raise the cap" for it to work and make actual difference in backlighting, that's where the changes via the Skylight and CoreBrigthenss APIs come into play I suppose?

**Comment by alin23** [comment]
Yes, the headroom needs to be slowly ramped up for this to work. 

The button should not appear on displays with non-HDR range. Is the [maximumPotentialExtendedDynamicRangeColorComponentValue](https://developer.apple.com/documentation/appkit/nsscreen/3180381-maximumpotentialextendeddynamicr) value greater than 0 on your MBA screen? That wouldn't make sense

**Comment by waydabber** [comment]
I think all modern Apple screens have EDR but that doesn't mean they are true HDR displays.

**Comment by alin23** [comment]
Searching for `headroom` in Console.app should shed some light on this. MBA might also have a nits cap by default and Lunar is probably just setting a too high headroom for it.

**Comment by waydabber** [comment]
I mean Apple does tricks like if you have an MBA for example and your screen is set to 70% brightness and play HDR content, it will progressively ramp up your backlight to 100% while compressing the luminosity of the non-HDR areas on your screen at the same time, except for the HDR content. This way the HDR content's bright scenes can rendered using this newly created "virtual" headroom. It is not true HDR, but if there is a HDR movie playing, the user does not notice the trick that is happening with the rest of the screen.

**Comment by waydabber** [comment]
(see this about this effect: https://prolost.com/blog/edr)

**Comment by alin23** [comment]
Yes, I know about that, I've also mentioned it in the HDR FAQ: https://lunar.fyi/faq#hdr-issue

But that wouldn't explain why the EDR value would be higher than 1. That is supposed to be a precise value that you can map to pixel values higher than 1.0 in the appropriate ColorSpace.

:sigh:

**Comment by waydabber** [comment]
I see things like this:

<<<< Alt >>>> fpSupport_GetVideoRangeForCoreDisplayWithPreference: displayID 1 reported potentialHeadRoom=2 wideColorSupported=YES marz=NO almd=NO deviceAllowsHDR=YES isBuiltinPanel=YES externalPanel=YES prefersHDR10=NO

**Comment by waydabber** [comment]
That was Safari. :) It seas potentialHeadRoom=1 for display2 (which is a standard SDR external display).

WindowServer says things like this:

<img width="792" alt="Screen Shot 2022-03-15 at 9 29 11" src="https://user-images.githubusercontent.com/37590873/158337019-eb89eb9b-6030-4c46-8c39-241f31e83521.png">

Besides this simply searching for Headroom does not yield results. Anyway have fun then. If you decide on how things work I'd be happy to include this in MonitorControl, but I understand that it's a secret for now. I don't have an XDR display to experiment on anyway.

**Comment by sagz** [comment]
After testing for a day, the display does seem to get brighter when I toggle XDR in Lunar but the UI is very inconsistent. Most of the time, when I'm at 100% in SDR mode, then I toggle XDR in Lunar main app (or the system tray mini UI)

Like this screenshot showing 70% in the bottom toast overlay but 100% in the top UI...
<img width="1555" alt="screen 2022-03-15 at 11 20 00@2x" src="https://user-images.githubusercontent.com/964843/158482183-90deb10a-483f-4b25-a3cd-35432141dadb.png">


I also feel that it doesn't 'stick' to 100% after a few minutes. Maybe the ambient light sensing based adaptive brightness overrides?

I have an Xrite i1DisplayPro I can measure things with but that'll take me a couple weeks due to scheduling issues.

This video shows this buggy interaction and lack of reliable affordance:
https://user-images.githubusercontent.com/964843/158446959-9f8a048b-8246-48a0-820c-f1392b28f3d5.mp4

**Comment by sagz** [comment]
After keeping 100% XDR brightness for a couple hours, my back screen is definitely warmer to touch :) (ambient temperature was 20ºC so i was mostly fine). I'll do thermal camera measurements after a couple weeks.

**Comment by alin23** [comment]
> Like this screenshot showing 70% in the bottom toast overlay but 100% in the top UI...

Looks like you haven't carefully read my comment about how to test 😅

I've said there that the XDR brightness has a separate slider OSD and it can only be adjusted through hotkey for now. I'm still thinking about where to place the slider for it. 

> I also feel that it doesn't 'stick' to 100% after a few minutes. Maybe the ambient light sensing based adaptive brightness overrides?

The system adaptive brightness is disabled while XDR is on. But there's a thermal throttle in the macOS kernel that will kick in when the display gets too warm. That is probably what you experienced.

**Comment by andrewdotcallahan** [comment]
Thank you for hacking this together! I've been playing around with the beta, and it all made sense once I figured out how I can now use the brightness keys to go "past" the normal 100% brightness. 

One surprise (probably it's system-level, but was surprising nonetheless) -- in some scenarios I observe cases where increasing the brightness level decreases the apparent brightness. E.g. on my 14" macbook pro, open to this page on safari with night shift on, XDR brightness 68 is just a touch brighter than 85. That's not true if night shift is off. Not a real issue, just a weird quirk of macOS.

I was not able to trigger the sub-zero brightness BTW -- not sure if I'm missing a relevant setting that needs to be ticked on.

**Comment by flatsiedatsie** [comment]
I feel lucky I found this, as I was working in the sun yesterday, and wished I could have a little more brightness from my M1 Macbook Pro display.

On first glance it seems to work. 

As someone who has never worked with Lunar before:
- Man, Lunar has a complex interface. It seems geared to creative professionals with lots of monitors. I would recommend releasing a second simple app that does only this one thing of increasing the brightness (and lowering into sub brightness, also wonderful). Keep it simple. Make it cost $5 and you'll have a winner on your hands.
- What nits level would you say the display can get up to now?
- I couldn't figure out how to enter the code you mentioned - it also requires an email address? Either way, it's not in a 14 day evaluation mode it seems, and it already working.

**Comment by alin23** [comment]
@flatsiedatsie 

That second simple app already exists as [Lunar lite](https://lunar.fyi/lite). 

It doesn't yet support XDR brightness because of App Store limitations, I'm trying to find a way to circumvent this. 

Sub-zero dimming is already possible by lowering the system brightness first then lowering the Lunar lite brightness _(they are independent, again because the App Store limitations don't allow the app to change the system brightness)_. 

----

From my tests with HDR content, the display can reach its full 1600nits until it's thermally throttled (or until you have more than ~70% of the screen as full bright white)

----

The license code probably expired already, but the 14-day trial is just as good. 

----

The risks are real, the lifespan of the LED will greatly shorten if used for prolonged periods of time. 

The macOS system has logic to throttle the display if it gets too hot, but if you use it in the sun, it might not be able to cool down fast enough. Heat is the biggest threat to these LEDs. 

If only parts of the screen are white, and if those parts move around, then this presents a smaller risk as it leaves time for the LEDs to cool down. 

I have no real numbers on the lifespan since these displays use new miniLED technology with smart throttling logic which has not yet been stress tested in the real world.

**Comment by flatsiedatsie** [comment]
> or until you have more than ~70% of the screen as full bright white
> If only parts of the screen are white, and if those parts move around, then this presents a smaller risk as it leaves time for the LEDs to cool down.

I plan to mostly use this with a coding IDE with a black background, so that doesn't sound like a problem. Brilliant.

I'll keep an eye on this to see if the lite version gains this ability before the trial runs out :-) Either way: this is a must-buy for me.

Thank you so much for working on this!

**Comment by flatsiedatsie** [comment]
In fact, I think I'll go catch some sun and test this out while I'm at it.

**Comment by alin23** [comment]
@flatsiedatsie Thank you for testing it!

@andrewdotcallahan there was a bug where XDR was being forcefully disabled by the system when also using external monitors. I managed to fix it and I'll release the update today.

> I was not able to trigger the sub-zero brightness BTW -- not sure if I'm missing a relevant setting that needs to be ticked on.

The sub-zero brightness kicks in as soon as you lower the brightness under 0. For the built-in, you have to **not allow the brightness to go to real 0**. There's a checkbox for that in the [Controls menu](https://app.lunar.fyi/display/builtin/controls) which should already be unchecked, but take a look at it just in case.

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/3819725/159118848-3e001d24-eda0-4fbd-9ff1-dc85ca9e7100.png">

**Comment by flatsiedatsie** [comment]
I am writing this from my balcony, sitting in the sun. It doesn't feel 3x brighter, but perhaps brightness experience is not linear? Either way, the extra boost is very welcome!

Make sure you email The Verge when you complete this, they will love this too.

**Comment by alin23** [comment]
> I am writing this from my balcony, sitting in the sun

Thanks for the view! :)

I am writing this from my desk which I haven't left in weeks because I really want to get this update out 😅 
I could use some sunlight...

Good idea about The Verge, I'll let them know.

----

>  >  For the built-in, you have to not allow the brightness to go to real 0. There's a checkbox for that in the Controls menu

>    Why? ìs there a risk to going to 0?
>   Why? Can't this be managed/detected automatically?

No risk. It just woudn't work because 0 brightness on the MacBook turns off the screen completely, so there would be no way to dim between `0.0` and `1.0`.

It is detected automatically and the **Allow brightness to reach zero** is unchecked by default on the MacBook. I just wanted to make sure @andrewdotcallahan didn't check it back.

**Comment by alin23** [comment]
Added in v5.5.1 🥳

**Comment by flatsiedatsie** [comment]
One more thing: I work in the field of privacy (but IANAL). Your software makes wayyyy too many connections to third party servers. Without informing the user too. This is not legal under the GDPR. Please take privacy more seriously? If this only happened because it was a beta version, then ignore this post.

**Comment by alin23** [comment]
Lunar only uses sentry.io for error reporting and licensing.lunar.fyi + paddle.com for licensing.

Where is the privacy problem?

**Comment by flatsiedatsie** [comment]
The problem is that I didn't see any privacy policy. In that policy you should probably disclose what information is collected, how long it's stored, where it's stored, if there is a data processing agreement with those third parties, etc.

**Comment by alin23** [comment]
Ok, I'll write some privacy policy. 

The thing is Lunar is an offline macOS app. It doesn't collect data and I would have no use for it anyway. What could I do with behavioral data?

It just checks if the license is valid periodically, sends error tracebacks when they happen, checks for updates. The usual things a macOS app has to do. 

The single useful data collected is anonymized monitor info which I use for cross referencing when I get the usual _"Lunar doesn't work for me"_ email with 0 information about what doesn't work. 

That data is also available for everyone at https://db.lunar.fyi so they can search for monitors that work with DDC and have the features they need when making a purchase decision. 

I'm not selling or storing any data.

**Comment by flatsiedatsie** [comment]
>  It doesn't collect data

Of course it does. You collect email addresses for user accounts, for one thing. That's personal data right there.

> What could I do with behavioral data?

I don't know. Keep in mind that meta-data is often behavioural data. More importantly, you use third parties. Those might in turn use third parties. It's like an oil slick, before you know it data spreads around. Hence the (legal) question: are your third parties classified as data processors? Do you have a contract with them that states what they are allowed to do with your users' data? Have you mapped out what the various legal grounds for the data processing are? If not, then that's worrysome.

> The single useful data collected is anonymized monitor info

That doesn't sound like a single piece of data. That sounds like detailed data about the user's system with a (pseudonomous?) user identifier.

> That data is also available for everyone at https://db.lunar.fyi/

Eh.. whoa. Bingo.

That uuid there.. that's not refering to the user is it? If so, get that out of there!
And that serial number... is that the actual serial number of the display? 

0_0

> I'm not selling or storing any data.

You literally say this after posting a link to an online database of user data!

**Comment by alin23** [comment]
Ok @flatsiedatsie let's stop making claims here because it seems you don't understand this "data" or these "requests". If you are looking for requests going out, you should be able to make your own judgment about what goes where, not guess. 

Open a proxy and look at the headers and body of the requests, you'll see everything.

I don't collect email addresses. users give them to Paddle when they buy a license. I only use the cryptographic hash to cross-reference monitor data, which is Lunar specific, random and impossible to tie to any user outside.

> That doesn't sound like a single piece of data. That sounds like detailed data about the user's system with a (pseudonymous?) user identifier. If it's pseudonymous, it's not anonymous. 

> That uuid there.. that's not refering to the user is it? If so, get that out of there!
And that serial number... is that the actual serial number of the display?

The UUID you see in db.lunar.fyi is an internal system UUID generated by macOS. It doesn't identify a specific monitor. It's not a user id.

The serial is not the Serial Number of the display, you can check for yourself on your own monitor. God knows what that value means but it's the same for almost all monitors from the same vendor.

> Keep in mind that meta-data is often behavioural data. More importantly, you use third parties. Those might in turn use third parties. It's like an oil slick, before you know it data spreads around. Hence the (legal) question: are your third parties classified as data processors? Do you have a contract with them that states what they are allowed to do with your users' data? Have you mapped out what the various legal grounds for the data processing are? If not, then that's worrysome.

Nobody else is using this data so there's no need for contracts, or any of this bullshit we have been talking about in the last few comments. Licensing goes through Paddle so everyone is free to consult their privacy policy when buying Lunar.

**Please understand that this will only create fear among users, and I'll start getting angry emails just like it happened with the guy that claimed Lunar was a web-based app, it used Electron and hogged all his CPU and RAM.**

---

By the way, we're on Github now, where Lunar's code is completely available. Can't you just check for yourself what data goes where in the code?

>  You literally say this after posting a link to an online database of user data!

I meant that I'm **not selling any data** and **not storing data that for myself** that users might not be aware of.

What the heck are we even talking about man? It's a frickin macOS app for controlling monitors.
