### ISSUE TITLE
Option to use homekit light sensor as data source

### ISSUE THREAD

**Issue by georgiypl** [alin23/Lunar#420]
### Name of the feature

Homekit light sensor support

### What problem does this feature solve?

Use any 3rd party homekit compatible light sensor instead of buying or making a custom wifi board  

### How should the feature work

1) "Homekit mode" option appears
2) App ask a permission to interact with a homekit (https://developer.apple.com/documentation/homekit/enabling_homekit_in_your_app) 
3) You may choose a sensor among connected, with homekit api  
(https://developer.apple.com/documentation/homekit/interacting_with_a_home_automation_network) 
4) You mac calibrate a conversion curve for the specific sensor  

### Visual description

![Untitled](https://user-images.githubusercontent.com/797688/140694616-82b02d28-e86d-42f8-b048-505179ca7b9d.jpg)

**Comment by alin23** [comment]
Thanks for the feature request!

Momentarily I'm way too busy with fixes on obscure setups, but I'll look into the HomeKit API as soon as possible.

**Comment by alin23** [comment]
This should be doable in a DIY fashion using the https://github.com/alin23/lunarsensor server.

Unfortunately a native solution is not possible because most HomeKit sensors report new data once every 3-5 minutes which is way too sparse for what Lunar needs. I wouldn't want to get into the world of supporting each sensor's particularities and having to explain this to confused users about slow Sensor Mode.
