### ISSUE TITLE
Unreliable hotkeys for input change

### ISSUE THREAD

**Issue by abecciu** [alin23/Lunar#427]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
MacBook Pro M1 Max 2021

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
DELL U4320Q and DELL U2717D

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-UUSB-C, miniDisplayPort-to-DisplayPort etc.):
USB-C-to-USB-C
USB-C-to-DisplayPort

- Using an USB Docking Station or Hub:
NO

- Lunar mode used (check it in the top-right corner of the Lunar interface)
Manual

- Yes, I ran Lunar diagnostics and DCC works on both monitors.

# Issue description:

When trying to change monitor inputs via hotkeys sometimes the hotkeys don't work. I couldn't find a pattern to detect when or how they stop working. Sometimes I hit the hotkeys multiple times and they don't work, but try after a couple of minutes and they work. There are times where they just won't work anymore. They way I found to fix it is to restart Lunar or to manually switch the input from the dropdown.

Here's a screenshot with the hotkey I have configured:
![Screen Shot 2022-01-03 at 3 56 16 PM](https://user-images.githubusercontent.com/38887/147993406-49d19f91-b527-48bd-8d3e-8456ed2a51a7.png)

Another thing that I noticed is that Lunar does not detect the input that's currently in use by the display. It will show whatever input value was last selected in the dropdown. See screenshot below. My current display input is "Thunderbolt 3 (DDC 25)" but Lunar shows "DisplayPort 1" in the dropdown which is the last option that I manually selected.

![Screen Shot 2022-01-03 at 3 55 49 PM](https://user-images.githubusercontent.com/38887/147993240-b4390798-8a3b-4dbc-a3e6-9401626af8bc.png)

I tried to enable the "Refresh values from monitor settings" option, but it didn't help to accurately keep track of the monitor input.

**Comment by alin23** [comment]
Hi @abecciu 

Most monitors don't allow reading the current input, that's why the dropdown only shows the last chosen input. It's a monitor limitation I can't do anything about.

On the hotkey part, that is also a monitor or macOS problem. If you switched inputs recently, the monitor hardware can stop accepting some DDC commands. 

Usually what fixes this is to start a new DDC connection, which is what happens when you restart Lunar.

I already refresh the DDC connection automatically when the monitor connects/disconnects or the screen configuration changes in any way, but it's still possible to get into this state because of monitor latency. 

Unfortunately there's no way to detect this, from the Lunar side everything looks like DDC is working as expected.

All you can do is to bind a hotkey to the Restart Lunar action to make it easier to recover from this when it happens again:

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/3819725/148032930-258bbb67-55ed-426b-b614-31a04051a4bc.png">
