### ISSUE TITLE
"Blackout" feature when display is connected to Macbook on boot already does not work

### ISSUE THREAD

**Issue by philippgerard** [alin23/Lunar#430]
# Issue details
- MacBook Pro 14" 2021

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Gigabyte FI32U

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C to DP

- Using an USB Docking Station or Hub:
    Razer TB4 Dock

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Auto: Sensor

# Issue description:
Using "Blackout" feature to turn off the Macbook display when connecting an external display works fine when the Mac is up and running already and Lunar is active. When I boot the Mac and Lunar only comes up after a while, things don't work, the external screen sometimes does not even come up at all. When I unplug and replug the dock, Lunar blackout works again.

IMHO, Lunar should check if the desired state is active every now and then and act accordingly.

**Comment by alin23** [comment]
Hi @philippgerard 

The decision for Blackout to work this way was made because it breaks the least amount of expectations. 

If Lunar would continuously check and reapply Blackout, the users might get into a state where they can't use the machine at all because the display could be turned off when it shouldn't. 

The users won't want to wait for Lunar to do the next check and re-unapply Blackout when the system state has stabilized. They'll just be angry and demand a refund. 

There's an incredible amount of edge cases in this Auto Blackout feature: 

- Disconnection events can be sent as soon as the monitor connects because macOS would start screen reconfiguration
- Mirroring can fail in the middle of applying it
- Monitors can appear and disappear several times in the screen list on system wake/boot

I found that the best way to deal with this is to automate as little as possible and make the behavior easily understandable. 

That's why Auto Blackout only does two things:

- Turns off the builtin display **when (not if)** the first external monitor is connected
- Turns back on the builtin display when the last external monitor is disconnected

**Comment by alin23** [comment]
About the external screen not coming up, that's not a Blackout problem. 

It's possible that your monitor is programmed to not turn on if it receives a DDC signal too fast. I've had other users report this. 

Try troubleshooting this connection problem with Lunar not running to make sure that it isn't a monitor-M1 compatibility issue in the first place. 

If it only happens when Lunar is running, try disabling the **Reapply values on wake** setting in [Advanced settings](https://app.lunar.fyi/advanced)

**Comment by philippgerard** [comment]
FYI: The problem of the screen not waking from sleep seems to have been resolved with the latest 12.3 beta of MacOS.

**Comment by alin23** [comment]
Thanks for letting me know! That's helpful in case I have other reports of it.
