### ISSUE TITLE
Lunar Feature: Explanation of the connection selection in preferences

### ISSUE THREAD

**Issue by patrickrushton** [alin23/Lunar#437]
I would really like to know what is the function of the connection selection in Lunar preferences? 

I have an external display connected via a Thunderbolt 3 to Mini DisplayPort cable. I don't know which of the Thunderbolt or DisplayPort options I should have selected for this display? 

Some explanation of what this selection actually does would be useful? Is it just for my convenience to remember how the display is connected, or does it change the functionality of Lunar somehow?

![image](https://user-images.githubusercontent.com/6472595/153208719-01829a2e-c68e-46b1-b656-927a22eb9c1b.png)

**Comment by alin23** [comment]
The inputs can't be explained. They are dependent of the capabilities of the monitor.

Some monitors have Thunderbolt on the DDC code 27, some on the 25 code, some (like my LG) even have it on DisplayPort 1. You just have to select an input to see what the monitor switches to.

**Comment by patrickrushton** [comment]
Thanks, I appreciate the answer even though I don't understand it :-)

DCC seems to work on my Dell on any of the settings (even when on Tuner or Component which are not actual physical inputs on my display). I guess so long as DCC is working for me, then I don't need to concern myself with the setting.

**Comment by alin23** [comment]
Oh I see, you don't understand what the dropdown does.

The dropdown is used to switch to another port of your monitor.

For example let's say you have:
* the MacBook connected to the Thunderbolt 3 port of the monitor
* a PC connected to a HDMI port of the monitor

This way, you can select HDMI 1 from the dropdown in Lunar, to switch the monitor to the HDMI port so that it shows the PC desktop instead of the MacBook desktop.
