### ISSUE TITLE
Lunar Bug

### ISSUE THREAD

**Issue by mjonuschat** [alin23/Lunar#438]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    MacBook Pro M1 13"

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Dell U3818DW

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    Thunderbolt -> OWC Thunderbolt 3 Dock -> miniDisplayPort-to-DisplayPort

- Using an USB Docking Station or Hub:
    Yes (Thunderbolt 3)

- Lunar mode used (check it in the top-right corner of the Lunar interface)
   Manual

- Tried Lunar Diagnostics?
> 1. Click on **Open Lunar Diagnostics** in the Lunar menu
> 2. Follow through the steps when asked

![Lunar Diagnostics menu item](https://files.lunar.fyi/diagnostics-menu-item.png)

    Yes

# Issue description:
Input Hotkeys don't work if set to also change Brightness or Contrast.
How to repro:

Set up Shift+Ctrl+Option+Command+X for Input Hotkey 1 to switch to DisplayPort 1 input
Enable "Apply Brightness" (set to 75/75 in my case) for DP 1 input

Set up Shift+Ctrl+Option+Command+V for Input Hotkey 2 to switch to HDMI 1 input
Enable "Apply Brightness" (set to 75/75 in my case) for HDMI 1 input

Result: Hotkeys don't switch the inputs of the monitor

Disable "Apply Brightness" for Input Hotkey 2
Result: Hotkey to switch to HDMI starts to work

Disable "Apply Brightness" for Input Hotkey 1
Result: Hotkey to switch to DP 1 starts to work

(Tested on Lunar Pro v5.3.2)

**Comment by alin23** [comment]
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/3819725/153552084-8e3a9bdc-e8e5-4444-819e-a197f42d2dc7.png">

I just tested this and it seems to work as expected.

Here's a video of me having the same settings you posted, and switching to DisplayPort 1 first *(which just blanks the monitor for a second and comes back on because that's the input I'm currently on)* then to HDMI 1 which blanks the monitor because there's nothing connected to that port.

https://user-images.githubusercontent.com/3819725/153552386-ccd8bad0-0375-43a2-a04a-fd2bc35699d6.mp4

I also looked through the hotkey handler code, there's nothing that could indicate a problem with the Apply Brightness setting. Maybe try restarting Lunar.

https://github.com/alin23/Lunar/blob/19b7f9436dda17fc995738741622dbdf41f11252/Lunar/Controllers/HotkeyPopoverController.swift#L64-L91

**Comment by mjonuschat** [comment]
This is super strange, I can reproduce it on two different Macs (13" MacBook Pro M1, 16" MacBook Pro M1) every time. Restarting Lunar and/or the Mac doesn't change a thing, here's a video of how it looks on my end. (You can hear the keyboard when I try to switch inputs):

https://user-images.githubusercontent.com/203423/153626184-499155a6-301d-4967-ab0b-a3c8a1b5e126.mp4

**Comment by alin23** [comment]
Maybe the problem is with the monitor. It might not accept input switching right after setting brightness and contrast. 

Maybe there needs to be a delay.

**Comment by alin23** [comment]
@mjonuschat here's a beta with a 1 second delay between applying brightness and setting input: https://files.lunar.fyi/Lunar-5.3.2-beta2.zip

**Comment by mjonuschat** [comment]
@alin23 That seems to be the issue, works fine in the version with the delay.

**Comment by alin23** [comment]
Ok, I'll add the fix for the next version. Thanks for reporting!

**Comment by mjonuschat** [comment]
Thanks for the quick fix
