### ISSUE TITLE
Lunar Bug: Can't Turn Off Blackout Without External Monitors

### ISSUE THREAD

**Issue by merchako** [alin23/Lunar#440]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
     MacBook Pro M1 Max 14" 2021

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Native (with Dell U2415 x2)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
     USB-C-to-DisplayPort cables (to non-effected monitors)

- Using an USB Docking Station or Hub:
    no

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Any (Sensor or Manual) with Blackout

- Tried Lunar Diagnostics?
    Yes

# Issue description:
BlackOut works great for external monitors, and engaging it on my native display works well, too—I can even use the keyboard shortcut <kbd>⌘</kbd><kbd>⌃</kbd><kbd>6</kbd>. Unfortunately, I'm having trouble disabling BlackOut.

1. I can black out my native display while externals are attached, but when I unplug it and walk away, the screen is still blacked out, and the keyboard shortcut doesn't work to turn it back on. I can only get my native screen to show by attaching an external monitor! I can't tell if (a) there's a dialog box I can't see, (b) I need to authenticate, or (c) there's just a bug, and <kbd>⌘</kbd><kbd>⌃</kbd><kbd>6</kbd> doesn't work.
2. After I black out one of many attached displays, I'll try to get it to show again with <kbd>⌘</kbd><kbd>⌃</kbd><kbd>6</kbd>. But instead of disabling BlackOut and showing the blacked-out screen, it just blacks out the next screen. This applies to both native and attached displays.

With these two problems—whether they're bugs or UX—it's really easy to turn off screen and really hard to turn them back on.

**Comment by alin23** [comment]
Yes, BlackOut is a bit fragile because of all the edge cases that come with mirroring. I'll try to improve this in the next version.

**Comment by alin23** [comment]
@merchako can you help me test this beta? [Lunar Beta 7](https://files.lunar.fyi/Lunar-5.3.4-beta7.zip)

I think I fixed issue 1 completely.

About the issue 2 I'm not sure as I don't have more than one monitor to test. I'd be grateful if you could test that as well. Just make sure to have the cursor on the mirrored monitor when pressing the hotkey.

**Comment by merchako** [comment]
Good news and bad news.

The good news is that I was unable to black out all the screens. 

It's a bit unpredictable. The behavior of <kbd>⌘</kbd><kbd>⌃</kbd><kbd>6</kbd> changed as I progressed with testing. Initially, <kbd>⌘</kbd><kbd>⌃</kbd><kbd>6</kbd> would only toggle the first screen I used it on. First <kbd>⌘</kbd><kbd>⌃</kbd><kbd>6</kbd> to hide it; second <kbd>⌘</kbd><kbd>⌃</kbd><kbd>6</kbd> to show it.

Things to look into

1. Timing seems to contribute to unpredictability. I did my second <kbd>⌘</kbd><kbd>⌃</kbd><kbd>6</kbd> relatively soon after my first <kbd>⌘</kbd><kbd>⌃</kbd><kbd>6</kbd>, which might explain the toggle-like nature behavior of just one screen. After that my timing varied much more. I also noticed that if I pressed <kbd>⌘</kbd><kbd>⌃</kbd><kbd>6</kbd> while the screens were still changing, it seemed not to affect anything (but maybe it did!—just not that I could see). 2. 
2. Sometimes upon <kbd>⌘</kbd><kbd>⌃</kbd><kbd>6</kbd>, a blacked out monitor would flash on (which is what I wanted) but then go back to black.3. 
3. After two monitors were black, I could sometimes get to one monitor black, but I could only get to zero monitors black with through Lunar Preferences.

Possible UX changes to consider:
1. Treat BlackOut like a stack, and have separate actions to push and pop screens from the stack. <kbd>⌘</kbd><kbd>⌃</kbd><kbd>6</kbd> adds the moused-over screen to the 
4. Add text to the Keyboard Shortcuts screen indicated that <kbd>⌘</kbd><kbd>⌃</kbd><kbd>6</kbd> applied BlackOut to the moused-over screen (not the focused screen).
5. Generalize the App Presets feature into a Presets feature, in which each preset can be triggered by many actions: keyboard shortcut, active app, open app, external display (dis)connected, and time of day or circadian rhythm. Then limit BlackOut to use in a preset, and you won't have to debug this.

**Comment by alin23** [comment]
Mirroring and screen reconfiguration is slow (mostly because monitors are slow so macOS adds artificial delays to avoid problems)

As a rule of thumb, you should wait at least 10 seconds between uses of the BlackOut hotkey. It's not something you would do in a real life scenario any way, and it's not our job to work against unknown hardware limitations.

I think you have some `blackOutEnabled` flags stuck as `true` from your previous tests, and that's why everything is so all over the place with these results.

#### Answers to _Additional (possibly unrelated) problems_

> When I unblack a monitor by clicking ⌽ in Lunar Preferences, the monitor reappears as expected, but when I unblack my native monitor by clicking ⌽, it doesn't. It's "on", but it's brightness remains zero; I have to click ⌽ and increase its brightness to get the expected result.

Sometimes the `brightnessBeforeBlackOut` value gets overwritten to 0, I'm not sure why yet, still investigating.

> My layout in macOS Preferences ▸ Displays gets reset if I disconnect a monitor while it's blacked out.

This happens because of disabling BlackOut forcefully on remaining displays. Disabling BlackOut will reconfigure displays and it's up to the system to go back to the previous state. Unfortunately the system seems to keep a very limited number of previous screen configurations and after about 4-5 different states it goes back to some default configuration.

#### Answers to _Possible UX changes to consider_

> Treat BlackOut like a stack, and have separate actions to push and pop screens from the stack. ⌘⌃6 adds the moused-over screen to the

This is not possible as I'm dependant on the mirroring state of the system which can change very unpredictably. The stack would be obsolete on the next system screen reconfiguration

> Add text to the Keyboard Shortcuts screen indicated that ⌘⌃6 applied BlackOut to the moused-over screen (not the focused screen).

The _applies to display with cursor text_ is mentioned in almost all places where BlackOut is explained. The hotkeys page is not fit for explanatory text. That page is already so packed that people are afraid to use it at all.

> Generalize the App Presets feature into a Presets feature, in which each preset can be triggered by many actions: keyboard shortcut, active app, open app, external display (dis)connected, and time of day or circadian rhythm. Then limit BlackOut to use in a preset, and you won't have to debug this.

That is a lot more complex than it sounds. I can't launch into another rewrite of Lunar which can surface a lot of other bugs, I already have two other apps that I currently work on as part of [The low-tech guys](https://lowtechguys.com/) and I need to focus on those. I just want to make BlackOut reliable.

**Comment by merchako** [comment]
Disregard what I wrote. If seems my OS switched to the non-beta version of Lunar midway through my testing.

**Comment by merchako** [comment]
Problem 1 is fixed.

The section below the horizontal rule still holds except for:
- Additional problem 1: When my native display is blacked out and I click ⌽ in Lunar Preferences, it correctly returns to visible brightness.
- Additional problem 2: I don't lose my layout when I disconnect/reconnect a blacked-out external monitor.

Sorry about the misleading previous comment. I've uploaded a video of testing to bring more clarity: https://youtu.be/o9UUh_HsS9k

**Comment by alin23** [comment]
This should be fixed in 5.4.3
