### ISSUE TITLE
Add a privacy policy

### ISSUE THREAD

**Issue by createcandle** [alin23/Lunar#444]
In response to https://github.com/alin23/Lunar/issues/417

> Open a proxy and look at the headers and body of the requests, you'll see everything.
> Can't you just check for yourself what data goes where in the code?

I don't see the average user doing that. "The user should have airsharked or looked through my code" is probably also not a valid legal defense if someone files a GDPR complaint :-D

> I don't collect email addresses. users give them to Paddle 

Under your orders. Hence the question about the "data processor" status. If you have a contract with Paddle, then legally speaking you collect them, and they only process them for you. If you have that contract, then you are responsible. If there is no contract, that implies they are not a data processor, which is worse, because that would mean _they_ are the owner of the account data, and you have no legal control.

> I only use the cryptographic hash to cross-reference monitor data, which is Lunar specific, random and impossible to tie to any user outside.

Great

> The UUID you see in db.lunar.fyi is an internal system UUID generated by macOS.

If that's not unique to a user, then there is no issue with leaving it in the dataset. If we're talking about a code that identifies a user (even if only to you), then legally speaking the dataset is still pseudonymous, not anonymous.

> Licensing goes through Paddle so everyone is free to consult their privacy policy when buying Lunar.

Then link to that. Either way, if you sell your product in the EU, then you should dive into the GDPR.

> What the heck are we even talking about man?

I'm giving you free advise based on my knowledge of the GDPR. Again, I am not a lawyer, but I do work in this field. I was trying to help you, for free, because I like what you built.

**Comment by alin23** [comment]
Done: https://lunar.fyi/privacy

The next update will also have a way to opt out of error reporting and anonymous data collection: 

<img width="845" alt="image" src="https://user-images.githubusercontent.com/3819725/159913376-0ccf7030-47a1-43bf-989b-5d22f24b3731.png">

In case this helps bring some peace to your mind, I worked for 2 years in information security as a Malware Researcher, so I am well aware of the dangers of exposing unwanted info. Since then, security and privacy has always been in the back of my mind.

I secure my servers well and use the least amount of data to get the job done. I don't use Google Analytics and despise anything that sells our data for advertising.

**Comment by createcandle** [comment]
Brilliant! Thank you so much for adding this, it's very much appreciated.
