### ISSUE TITLE
Issues with certain Samsung monitors

### ISSUE THREAD

**Issue by lijunkang12** [alin23/Lunar#45]
I have been trying to use Lunar with several different models of Samsung monitors. Lunar does not work properly for some of them.

It works perfectly when connected to U32R590C with DisplayPort 1.2.

However, when connected to U28H750 with DisplayPort 1.2, contrast cannot be adjusted.

And when connected to U28E590D or to C24F390 with HDMI 2.0, neither brightness nor contrast can be adjusted.

**Comment by lijunkang12** [comment]
Today I have experimented and found out that it is possible to adjust brightness (but not contrast) when connected to U28E590D with DisplayPort 1.2. So I wonder maybe Lunar does not work with HDMI connection?

**Comment by alin23** [comment]
This is a problem with either the connection cable or the monitor firmware handling the DDC messages. 

Lunar is simply sending standard DDC messages for `brightness write` and `contrast write`. It's up to the monitor to interpret that and adjust the values accordingly. There's no custom logic based on the monitor brand or type of connection.

In my experience, most of the time the problem is in the cable used (or adapter/hub/dock if one is used) as most modern monitors implement DDC as expected. So try to debug the problem by switching cables between monitors.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lijunkang12** [comment]
I see. Thanks for your reply!
