### ISSUE TITLE
While Lunar is running, (XDR) HDR is broken

### ISSUE THREAD

**Issue by greybaron** [alin23/Lunar#450]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    MacBook Pro 2021

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    internal XDR display

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

# Issue description:
When viewing HDR content on YouTube (didn't try other sources), when Lunar is running the peak brightness is same as SDR, and all higher brightness levels are the same brightness.

After restarting Lunar, HDR is restored, until either the brightness is changed, or the HDR content is off-screen once and then shown again.

**Comment by alin23** [comment]
@greybaron I found a possible workaround for this macOS bug, would you be willing to try a Lunar beta and report back if it works?

**Comment by alin23** [comment]
Here's the beta if you want to try it: https://files.lunar.fyi/Lunar-5.5.5-beta8.zip

Make sure Lunar's XDR Brightness feature is disabled when testing this, as it's not possible to have both 1000nits SDR brightness and HDR videos.

Also make sure you're not using Gamma dimming or f.lux as those too will disable HDR.

**Comment by greybaron** [comment]
Thank you, I've tried it. HDR now works (mostly), only when changing brightness, after a second it goes back to the old behavior for about 2 seconds. Also when hiding and then returning to HDR it does this flicker sometimes, but otherwise the fix seems to work!

**Comment by alin23** [comment]
The flicker is caused by the system. You can check that it happens without Lunar as well, at least for me it does.

The fact is, this HDR enabling on-demand that macOS does, involves a lot of work and it is a bit slow, which is why you see the flickering while the system is ramping up the LED backend. 

It's also why you don't see many monitors doing the same thing. Most of them have a checkbox/setting through which you enable HDR or don't. You can't have both HDR and SDR at the same time like on the MacBook display.

Anyway, let me know if you see any other oddities. I'll try some more stuff, but I suspect this is the best I can do until Apple fixes this.

**Comment by alin23** [comment]
There's a workaround for this in v5.6.1.

This is still a macOS bug so a real fix should come from Apple.

**Comment by amon-666** [comment]
here was the same problem, but it was resolved after "Run in HDR compatibility mode" option turned on.
