### ISSUE TITLE
Custom HUD (XDR/sub-zero) overlaps with macOS' native HUD

### ISSUE THREAD

**Issue by jankais3r** [alin23/Lunar#477]
Hi,

Thanks so much for Lunar, a really awesome app.

The only issue I have is that the custom secondary slider for XDR and sub-zero brightness covers the bottom of the macOS' native brightness indicator, which makes it more difficult to quickly return to max SDR brightness without "overshooting". Could you maybe make the custom HUD movable, or just shift it a bit by default? This issue is on a 14" MBP in case that matters.

<img width="361" alt="sub-zero" src="https://user-images.githubusercontent.com/2159464/182497554-d9d8c27e-e78c-4395-bc20-f31c610f5fdc.png">

<img width="359" alt="xdr" src="https://user-images.githubusercontent.com/2159464/182497572-80a0cab8-9321-4b24-8e32-6a169c6e328e.png">

**Comment by alin23** [comment]
Unfortunately it's not possible to read the position of the native OSD and place the XDR based on it. 

I placed it so that it doesn't overlap and looks good on my end, but it's normal for it to look different on another resolution. Making it movable will make code and UI a lot more complex for such a minor thing, and I have to choose wisely what I add to the UI as it is already become too complex for the average user.

**Comment by alin23** [comment]
I can add a hidden verticalOffset setting if that will help. I'll publish an alpha with the change tomorrow.

**Comment by jankais3r** [comment]
Hi Alin, I see that a new alpha was pushed yesterday. Is the verticalOffset config option included?

**Comment by alin23** [comment]
I just uploaded alpha4 that should fix this without the need for an offset.

It seems that the only difference on your side is that you have the Dock showing, while I have it hidden. That changes the `screen.visibleFrame` height.

I adjusted the code to not take into account the Dock height and allow overlapping the Dock.

**Comment by jankais3r** [comment]
Works great, thank you very much!
