### ISSUE TITLE
If you open preferences from menubar, have to close menubar first

### ISSUE THREAD

**Issue by alana314** [alin23/Lunar#481]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
Macbook pro Monterey 12.3.1

- Tried Lunar Diagnostics?
No

# Issue description:
If I click on the Lunar menu icon, then click preferences, the menu stays open, and the main application window isn't interactive until I click to close the menu icon.

<img width="962" alt="Screen Shot 2022-08-14 at 10 28 52 AM" src="https://user-images.githubusercontent.com/1194589/184548151-ef2739b0-8720-4a86-9881-a440621bed91.png">

**Comment by alin23** [comment]
The problem is actually that you can't click right under the menu bar menu. You can click on the left and right of it. 

This happens because I made the height of the menu fixed to the screen height to allow for dynamically adjusting the menu density. It's a workaround we'll have to live with until Apple fixes the dynamic height issue.
