### ISSUE TITLE
The "non-responsive display" dialog buttons don't work correctly

### ISSUE THREAD

**Issue by mattclarkdotnet** [alin23/Lunar#499]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac M1, Mac Mini M1, Hackintosh etc.):
    Mac Studio

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    Dell U2718Q and Dell S2721QS

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C to DP

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Sensor

- Tried Lunar Diagnostics?
   Yes

# Issue description:
When the "non responsive display" dialog appears, clicking "Not now" causes the "Yes" button to show blue (although the effect seems to be correct that the display continues to use DDC).  Also it can often take more than one click for the dialog to respond.

https://user-images.githubusercontent.com/648794/209901822-cecc4886-0281-4336-9133-8028f604e525.mov

**Comment by alin23** [comment]
Not a Lunar problem. That happens because the dialog is not in focus, something else on your system stole focus from Lunar.

**Comment by mattclarkdotnet** [comment]
If you watch the video carefully, you will see the mouse click is on "Not now", but the "Yes" button turns blue.

The multiple clicks thing isn't focus stealing I'm sure, because sometimes it takes up to 3 clicks, which is why I think it's related to the main issue with the wrong button responding to the click.

**Comment by alin23** [comment]
The confusion here is that you thing that clicking a button should make it blue. macOS doesn't make the button that you click blue. 

There's a button that's specified as _main_ button which is always blue, and in this case it is the **Yes** button because I wanted the user to select Yes when pressing Enter.

**Comment by mattclarkdotnet** [comment]
But it doesn't make sense to have a choice of actions, then give feedback to the user (turning blue) for the same action each time, regardless of where they click.

No other button or other interaction item in MacOS that I can find behaves this way.  The item being clicked is always the item that changes colour or shade, or otherwise responds.

It's only a small thing but it's odd!

**Comment by alin23** [comment]
The button is not changing color on click. Every macOS Ventura dialog works that way: there's a main button that's always blue and reacts on enter, then there are secondary buttons that are gray. That's the active state when the dialog is in focus. 

The inactive state, when the dialog is out of focus is when all the buttons are gray until you focus the dialog back. 


The buttons will show a bluish tint when clicking them to show feedback but, in your case that does not happen because the dialog is out of focus, so when you click the button, that's also when you transition the dialog from out of focus to in-focus and the system doesn't have time to also show the tint, it just shows the active state.

**Comment by alin23** [comment]
Here's a video that shows this behaviour happening for the simplest macOS native dialog: https://shots.panaitiu.com/BWHB56RC

And the code for it:

```swift
import Cocoa

let window = NSWindow(
    contentRect: NSRect(x: 0, y: 0, width: 100, height: 100),
    styleMask: [],
    backing: .buffered,
    defer: false
)
let alert = NSAlert()
alert.messageText = "Non-responsive display"
alert.addButton(withTitle: "Yes")
alert.addButton(withTitle: "Not now")
alert.addButton(withTitle: "No, never ask again")
alert.beginSheetModal(for: window) { response in
    if response == .alertFirstButtonReturn {
        print("User clicked Yes")
    } else {
        print("User clicked No")
    }
    exit(0)
}

NSApplication.shared.run()
```

**Comment by mattclarkdotnet** [comment]
I feel like a total idiot.  15 years of using a Mac and I never noticed this before and now I can't unsee it!  Sorry for wasting your time.
