### ISSUE TITLE
Usb-c macbook + usb-c dock + hdmi + dell u2715h monitor

### ISSUE THREAD

**Issue by giulioungaretti** [alin23/Lunar#5]
I think the app does not change the brightness at all :D  Is the app supposed to work with the mentioned hardware? 

Let me know if I can report more details // logs in case it's meant to work :D 

And thanks for making this open source!

**Comment by alin23** [comment]
Sorry for the delayed response, I rarely remember to check Github notifications. It's really hard to tell which setup would work and which wouldn't. 
Basically, if the monitor implements DDC and you're using a connection that supports DDC command interface (which I think includes HDMI, USB-C, DisplayPort and VGA), then Lunar should work. I'm really just working with the standards.

A dock between the monitor and the Macbook might be a problem for DDC/CI but I can't be sure.

The first (and easiest) thing you can do is to look through the monitor's settings and try to find the DDC setting. Make sure that's turned on (check page 44 here: https://static.bhphotovideo.com/lit_files/104996.pdf#page=44)

If that's enabled, check to see if your dock's HDMI port supports DDC.

Most of the DDC logic is borrowed from this project https://github.com/kfix/ddcctl/
You can try manually running that tool to see if DDC commands work for you.

**Comment by giulioungaretti** [comment]
@alin23 no worries! thanks for the answer! Will check and report back!

**Comment by giulioungaretti** [comment]
@alin23 ddcctl reports a failure to send the DDC command, so it looks like it must be the usb-c dock! The monitor does indeed support DDC/CI and it's on.
I may try with a  usb-c->HDMI simple adaptor just to make sure!

**Comment by alin23** [comment]
Thanks for testing! Yes, a direct connection would be a good idea. Too bad you can't use Lunar through the dock..

**Comment by kirmorozov** [comment]
Works well for me with dell p2415q(I'm sure dell has same internals) with type-c->hdmi adapter.
So most likely dock is the reason.

**Comment by alin23** [comment]
Yes, more users emailed me with the same issue because they were using a dock. I don't think there's much I can do here unfortunately. I'll add a notice on the website on the next Lunar update ^_^

**Comment by forivall** [comment]
I'd really like to start a list of docks that do properly forward the DDC/CI data. It's really frustrating.

**Comment by alin23** [comment]
@forivall I started doing that but I kept getting reports where the same dock would work for someone and wouldn't work for another user. That's because the whole combination of GPU, Dock, cable, connector and monitor needs to support DDC properly. We simply can't make such a list. I also have a Thunderbolt 3 Dock with an HDMI connector that works with two of my cables but not with my third. And you can't really label cables, especially after you got them out of their packaging.

I think the way to go is to pick 2-3 worldwide available docks and 2-3 cables per connector that we know are working and feature them on the official website. Whoever needs a safe recommendation could choose the combination that works for them from that list. What do you think?

The GPU and the monitor.. well we can just assume they work properly. The only GPU + connector that gave me a lot of trouble in the Mac world is the Mac Mini GPU with its HDMI connector. Everything else worked as expected.

**Comment by forivall** [comment]
I left a bunch of questions on Amazon and out of all of them, Anker docks claim to support it. It's worth a shot to try them if someone is looking for a dock.

**Comment by forivall** [comment]
I can confirm that with https://www.amazon.ca/gp/product/B07PPGWQ15, DDC/CI does work (i'm using https://github.com/MonitorControl/MonitorControl and not Lunar tho), on my MacBook Pro (15-inch, 2019)
