### ISSUE TITLE
Advanced Presets

### ISSUE THREAD

**Issue by ozum** [alin23/Lunar#510]
Hi,

### Name of the feature

Advanced Preset

### What problem does this feature solve?

At night I use low brightness with low blue color:
* Brightness: 0%,
* Contrast: 25%,
* DDC Led Color RGB: 50%, 45%, 40%

During the day I use full brightness:
* Brightness: 100%,
* Contrast: 50%,
* DDC Led Color RGB: 75%, 75%, 70%

Current presets only change brightness and contrast and I have to dive into sub-menus to change the advanced settings by hand. It is very useful if every setting (whatever can be adjusted in advanced settings) can be stored in a preset.

### How should the feature work

A checkbox can be added preset saving section. If the checkbox is selected, preset saves all settings including advanced ones. If the checkbox is not selected, the preset save only basic settings as before.

### Visual description

Every setting including advanced settings seen as below (Color, DDC , Controls, etc.)

![image](https://user-images.githubusercontent.com/1497060/220041732-fad69ac7-da7d-4f53-b2f4-537e785f3833.png)

**Comment by alin23** [comment]
Hi @ozum 

Thanks for the feature request!

Unfortunately Lunar is already too complex to understand for less technical users, so I'll be working on removing complexity for the next few months, instead of adding even more.

What you want is something that's rarely needed, and also rarely works as most monitors don't implement the DDC color controls. 

But fortunately if you're using macOS Ventura, all this can already be accomplished using the [macOS Shortcuts support](https://lunar.fyi/#shortcuts) in Lunar.

![image](https://user-images.githubusercontent.com/3819725/220117576-b4943a42-c121-46fa-aaf2-b72b88d30bdc.png)

**Comment by ozum** [comment]
Thanks for the help.
