### ISSUE TITLE
Does the 'Read Monitor Brightness Periodically' setting belong in the drop-down menu? 

### ISSUE THREAD

**Issue by DamiansDesign** [alin23/Lunar#56]
This is not so much an issue, more a suggestion. 

Does the `Read Monitor Brightness Periodically` setting need to reside in the main drop-down menu where it is so easily enabled? Perhaps it should be in settings, so it's not so easy to enable.

I had a small issue this morning when waking my iMac where my external display brightness wasn't changing, even though it was working before I put the machine to sleep the previous night. I noticed the new `Read Monitor Brightness Periodically` setting in the drop-down menu, and for some reason I thought it should be ticked --I must have confused it with the polling value in settings, thinking this setting wouldn't freeze my machine. It froze my machine, completely! No mouse, no keyboard, no 'force quit'. I was forced to reboot, only to have my machine freeze again because Lunar starts at launch --yep, I can definitely confirm Lunar starts at launch now. :) Thanks for fixing that! :))

I wasn't able to disable it using `defaults write site.lunarapp.Lunar refreshBrightness 0`, I had to change it manually in the preferences file.

It was frustrating for me, an experienced macOS user, so I can only imagine what it would be like for a less experienced user.

I presume there is no way of checking if the display supports this setting?

What is this setting actually for; what is it supposed to do?

Thanks for your ongoing efforts with Lunar, it's greatly appreciated.

**Comment by alin23** [comment]
# What the setting does
The setting activates a service that reads the brightness and contrast from the monitor periodically and also when Lunar starts or a monitor is connected.
This alleviates some issues other users have when the monitor brightness was changed from the hardware controls of the monitor:
1. Lunar shows the wrong brightness in the UI in Manual mode and in the Quick Actions popover
2. Using the hotkeys to increment/decrement the brightness sets a wrong value because Lunar increments the value stored in the app memory, not the actual monitor value (there's no command for that)
3. When Lunar starts or a monitor is connected, smooth transition will start from the last known brightness instead of from the actual monitor brightness

# Why it's implemented in this silly way
Users have asked for this feature for a long time, although I kept saying that most monitors don't support this. So when I finally implemented it, Macbooks have started freezing all over, so users have asked to make this disabled by default but also make it an option.

So I put it in the menu with a big and ugly caution under it. I could make it ALL CAPS if that helps, but curiosity will still win over caution. I don't have any more space in the settings page to add this. And I'm sure it won't help either. 

I added some more troubleshooting instructions in the README to make this a little less frustrating: https://github.com/alin23/Lunar#troubleshooting

One bright side is that the guy that created the DDC logic found a way to make more monitors work by adjusting the DDC reply wait time based on the GPU used: https://github.com/kfix/ddcctl/commit/0fe2ef4a8c66ab9a64c7e089f8b4a1953bff0556

When I'll have some free time, I'll try to write a GPU detection logic that adjusts that parameter dynamically to make this work for everybody (hopefully).

**Comment by DamiansDesign** [comment]
@alin23 thank you for the detailed (and quick) response.

Ah, OK so it's for reading the external display *not* the built-in display. That's where I was getting confused; thinking it was something with 'Polling' the built-in display.

It might be worthwhile (if possible) to change the wording to something like: "Read **External** Monitor Brightness Periodically".

> So I put it in the menu with a big and ugly caution under it. I could make it ALL CAPS if that helps, but curiosity will still win over caution. I don't have any more space in the settings page to add this. And I'm sure it won't help either.

I doubt ALL CAPS will help. Curiosity will certainly win over caution, as will (like in my case) a misunderstanding as to what it was (me thinking it was for polling the built-in display).

> I added some more troubleshooting instructions in the README to make this a little less frustrating

Great. Thank you!

> When I'll have some free time, I'll try to write a GPU detection logic that adjusts that parameter dynamically to make this work for everybody (hopefully).

This looks promising. :)

Thanks again for your efforts!! :))
