### ISSUE TITLE
Lunar Diagnostics Report [https://transfer.sh/HmHO3/lunar.log]

### ISSUE THREAD

**Issue by souljazzfunk** [alin23/Lunar#62]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    No

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro early 2013

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    mac - HDMI - DVI - monitor

- Using an USB Docking Station or Hub:
    No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Sync, Location or Manual*

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    External display is recognized, but no control

# Issue description:

**Comment by alin23** [comment]
I suspect that the DVI connection might be the issue here. If you have the possibility, please try a different way to connect the monitor like direct HDMI or DisplayPort. If ddcctl doesn't work, then your monitor is not getting or responding to DDC messages and Lunar can't do anything.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by souljazzfunk** [comment]
ok I'll try!  thanks for what you're doing!
