### ISSUE TITLE
Lunar menu disappears.

### ISSUE THREAD

**Issue by lukerooneyio** [alin23/Lunar#64]
# Issue details
- MacBook Pro 2017:
- Benq 4K Monitor
- Displayport through Thunderbolt 3 Dock:

Sometimes when I adjust the brightness of my monitor the lunar menu won't pop up. It's seems random, sometimes it works, sometimes it doesn't.

Also the Lunar menu bar icon has been missing. I use bartender, but it doesn't appear to be working correctly with Lunar's menu bar icon.

**Comment by alin23** [comment]
Thanks for reporting this!

There's nothing special that Lunar does with the menu bar icon, it's a standard icon like for every other app. I also use Bartender and it has always worked with Lunar so the issue must be elsewhere.

The menu tries to appear right under the menu bar icon, but if the icon is not visible in the menu bar (because Bartender hides it, or because you are in a fullscreen space) then it's undefined where the Quick Actions menu will appear. It's possible that for you it appears off-screen so you can't see it. Try to always show Lunar icon if you want to take advantage of the Quick Actions menu.
