### ISSUE TITLE
Lunar Diagnostics Report [https://transfer.sh/2PU6j/lunar.log.enc]

### ISSUE THREAD

**Issue by p4k4** [alin23/Lunar#67]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
Yes, within a small range.

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
Hackintosh

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
USB/TB2

- Using an USB Docking Station or Hub:
No

- Lunar mode used (check it in the top-right corner of the Lunar interface)
All

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
On both Thunderbolt Cinema Display's, when setting the brightness to 100%, the result is not the true 100% brightness of the displays (more like 50%). The problem is that it seems the range at which Lunar see's 0-100 is actually 0-50 by the time those values pass to the displays.

**Comment by p4k4** [comment]
So basically from what I can see - The brightness values of Lunar fo not map correctly to my displays.

I have a desktop environment with two 27" thunderbolt cinema displays connected via DP and USB.

When I put a flashlight on the sensors, brightness will raise (showing higher than 100 in Lunar) then suddenly it'll "snap" the brightness value back down to what Lunar thinks is "100".

**Comment by alin23** [comment]
Hi @p4k4 

Thanks for the report! From what I gather, the Cinema display supports setting brightness through Apple CoreDisplay framework and has a range of 0-255 instead of 0-100.

Can you please test this version of Lunar that adds special support for Cinema displays? https://transfer.sh/xtDsu/Lunar-2.9.11.dmg

While you're at it, can you also help me test some experimental features I had in the works anyway?
1. Check if media keys work. You can check that by pressing brightness and volume keys while you have the cursor on the external monitor.
2. Check if the volume changes with the volume hotkeys when you have the monitor audio output selected (I don't know if the Cinema display has audio support though)
3. Check if you get the native On-Screen Display showing when changing brightness/contrast/volume with the hotkeys

**Comment by alin23** [comment]
This should be fixed in 3.0.0. Feel free to reopen if the issue persists.
