### ISSUE TITLE
Lunar Diagnostics Report [https://transfer.sh/gSLmR/lunar.log.enc]

### ISSUE THREAD

**Issue by gngan1** [alin23/Lunar#68]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    No. I have one iMac Pro connecting to two identical external LG 32UL950. (1) only 1 LG display responses to brightness adjustment.

- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
  iMac pro

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
   Both external displays are connected by DisplayPort 1.4 cable/

- Using an USB Docking Station or Hub:
StarTech.com Universal Thunderbolt 3 or USB-C Host Docking Station

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    *Sync, Location or Manual* All modes don't work.

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
Answered in Q1. However, when I use TB3 cable to connect iMac Pro and to only one external LG display, Lunar can control the brightness of both iMac's and LG's display.

**Comment by alin23** [comment]
Hi @gngan1 !

I see a lot of errors like this in the log:
```
Error writing brightness using DDC 
["name": "LG HDR 4K", "id": 459139738, "serial": "C4D04DC5-98B9-6366-E6F2-2189C7686AC3"]
```

Lunar sees both monitors and sends DDC messages to both of them but it seems that the connection between the iMac and the monitor can't pass the message to one of the monitors.

Unfortunately there's nothing that I can do in software to fix this. It is a hardware connection problem and to solve it you probably have to connect the monitors to separate ports of the iMac, bypassing the Startech hub.

**Comment by gngan1** [comment]
Thanks for the reply. 

This is fine. Having the ability to control one LG display by keyboard is still better to toggle the display’s joystick!

With best regards
George

**Comment by alin23** [comment]
@gngan1 since you have multiple monitors, would you like to help me beta test a Lunar version with support for changing volume, and displaying native OSD? I only have one monitor and can't test if it works.

You can find the beta version here: https://transfer.sh/13FEqN/Lunar-2.9.11.dmg

What I'd like to know:
1. Check if media keys work. You can check that by pressing brightness and volume keys while you have the cursor on the external monitor and seeing if the brightness/volume actually changes.
![image](https://user-images.githubusercontent.com/3819725/75254418-a1f99280-57e0-11ea-8ff8-765ef0590f15.png)
![image](https://user-images.githubusercontent.com/3819725/75254440-aaea6400-57e0-11ea-8769-e2b8014a5c4c.png)

2. Check if the volume changes with the volume hotkeys when you have the monitor audio output selected. The default volume hotkeys are CTRL+F11/F12 or the volume media keys if point 1 works.
![image](https://user-images.githubusercontent.com/3819725/75254276-6b237c80-57e0-11ea-98e1-01a27ad557ff.png)

3. Check if you get the native On-Screen Display showing when changing brightness/contrast/volume with the hotkeys.
<img width="208" alt="Screenshot 2020-02-25 at 15 04 27" src="https://user-images.githubusercontent.com/3819725/75254160-34e5fd00-57e0-11ea-884a-abd5948547ff.png">

**Comment by gngan1** [comment]
Hi

Thank you for the suggestion.

I’m working on my research quite intensively at the moment. Testing you nice software will likely require disconnecting one and two displays from the tb3 dock in turn and to connect them directly to the iMac and risk system freeze and reboot.

I’ll be more available a month from now and will definitely beta test ur app.

Best regards
George
