### ISSUE TITLE
Monitor Volume OSD being triggered when external audio output connected.

### ISSUE THREAD

**Issue by cumanzor** [alin23/Lunar#73]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    MacBook Pro 2016 15".

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    LG 4K (27UD68-P)

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    USB-C to DP.

- Using an USB Docking Station or Hub:
   No.

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    Manual

# Issue description:
The new external monitor volume control feature is being enabled when the output device is anything BUT internal audio. That means that if you use an external USB DAC, the audio OSD on the monitor is being triggered as well. 

Not a big deal but it's distracting, and there's no option to disable the monitor audio controls it seems.

**Comment by alin23** [comment]
Yes I overlooked that. Thanks for letting me know!

I'll try to come up with a solution by tomorrow.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alin23** [comment]
Unfortunately there's no way to tell which audio device belongs to which monitor. I can only detect if the current audio device can be controlled by the system or not.

I updated the logic in Lunar 3.1 to only override media keys if the current audio device can not be controlled by the system which is a common thing for monitors. If the DAC audio device also can't be controlled by the system then Lunar will still override the volume keys because it can't tell that it's not a monitor audio output.

If you experience that, please let me know of a better way to handle this case as I haven't found any.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cumanzor** [comment]
Thanks for looking into this. An option would be to make the "Use Media Keys as Hotkeys" into two separate options, one for brightness (which I use), and one for audio (which triggers the monitor audio OSD even if the audio device is not the monitor). 

Honestly though now that I think about it this isn't a particularly big deal to me, I can just use the controls from the DAC directly.

**Comment by alin23** [comment]
Thanks for the idea!

I'll close this issue as it isn't really fixable as I want. I'll reorganise the menu items that are rarely touched into the Lunar UI and I'll split the _Use Media Keys_ option as you recommended.
