### ISSUE TITLE
Suggestion: Volume hotkeys should affect the selected audio device, not the monitor on focus.

### ISSUE THREAD

**Issue by fservant** [alin23/Lunar#74]
Hi,

Thank you for this awesome software! It gets better and better, particularly with the new functionality of changing volume and hotkeys.

Let me clarify this issue. For brightness, it makes sense for hotkeys to affect the monitor on focus. But for volume, it's a bit different. The device "on focus" is the audio device that is currently selected in MacOS as output. 

When I am using an external monitor and listening to music on my headphones connected via cable or bluetooth to the Mac, I want hotkeys to affect the device that is currently selected as output, not the monitor's output.

Thanks!

**Comment by alin23** [comment]
Thanks for the feedback! I indeed that's also how I wanted this to work but for the moment I couldn't find any way to link an audio device to a monitor. 

The thing is Lunar is not using the system audio API to change the volume because that doesn't work on monitors. I'm changing the volume through DDC and that means that I have to change the volume of a specific monitor. There's no such thing as current audio device when using DDC. 

So to fix this I have to find a way to tell which monitors is selected as the current audio device and only send DDC messages to that one. I'll think about it but for now there's no obvious solution.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fservant** [comment]
Wow, thanks for such a quick response!

Have you considered using the system audio API to check if the external monitor is selected as the audio output device or not? If it is, then you can change the volume through DDC. If not, then you delegate the volume change to the system.

As a workaround, you could also have two separate options to hook media keys to Lunar, one for brightness and another for volume. That would allow the user to benefit from the media keys for brightness, but keep the old behavior for volume.

Thanks again!

**Comment by alin23** [comment]
I am actually using the system audio API to check if the current audio device can be controlled by the system and disable Lunar volume keys when that is valid. 

But the API doesn't tell me if that device belongs to a specific monitor or even something else like a DAC. So if you have two monitors for example and you select one of them as audio output, I have no way to know which monitor you selected from the current available APIs. That's why I leave it to the user to select which monitor to send the volume commands to based on the cursor position. It's the only solution I could think of now.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fservant** [comment]
Oh, I see. Thanks for the clarification. Then, the behavior that I am seeing must be a bug. These are the steps to reproduce:

1. Open Lunar
2. Place mouse on the external monitor.
3. In the system's audio drop-down menu, select audio output to be the external monitor.
4. Change volume level (it correctly changes the monitor)
5. In the system's audio drop-down menu, select audio output to be the plugged-in headphones.
6. Change volume level (it still changes the monitor, which is incorrect)

7. Quit Lunar and open it again.
8. Change volume level (it now changes the plugged-in headphones level, which is correct)

Thanks again!

**Comment by alin23** [comment]
Yes it is a bug and I'm working to fix it but this might also be a problem with the system's CoreAudio getting stuck so no matter what I do, it might still happen occasionally.

**Comment by alin23** [comment]
This should work as expected in Lunar 3.1 which is Lunar should only override the volume keys if the current audio device can not be controlled by the system (common for monitor audio output).

Let me know if the issue persists.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fservant** [comment]
Hi. I'm sorry, but version 3.1.0 still has the same problem, with the same steps to reproduce :(

**Comment by alin23** [comment]
I can't reproduce it, it's probably a CoreAudio inconsistency on your part. Lunar is listening for audio device change events from CoreAudio and looks like on your side the change event happens when you select the monitor device but doesn't happen when you select the headphones.

I've had many troubles with CoreAudio hanging because of Bluetooth or Airplay devices, it really isn't that reliable but it's all we got.
