### ISSUE TITLE
Coarse brightness and volume adjustment

### ISSUE THREAD

**Issue by unknowndomain** [alin23/Lunar#77]
### Name of the feature

Fine and coarse adjustment of brightness and volume levels

### What problem does this feature solve?

Currently adjusting the brightness and volume with the new media key funciton is a bit slow due to the number of presses required.

This is because Lunar is not emulating the default behaviour of macOS correctly.

### How should the feature work

Normally in macOS there are 10 levels of brightness or volume between 0% and 100%, I would suggest that this should be the default behaviour of Lunar and that the fine adjustment mirror macOS which uses Shift + Option with the relivent key to adjust half levels as Lunar is currently doing.

**Comment by alin23** [comment]
The step is configurable from the Configuration page of Lunar:
![image](https://user-images.githubusercontent.com/3819725/75696961-1044c600-5cb5-11ea-8cf4-5d81fbcb4442.png)

Of course, it would be great to also have fine adjustment hotkeys. Lunar already has that logic implemented but it is not enabled because I don't know how to make it visible. There's already so much stuff going on in the UI..

I'll add fine adjustment hotkeys and make the current step bigger by default. What I can't do is match the system brightness adjustment because the built-in display has more steps available (I think 128 or 256) instead of just 100 for the external monitor. So we'll always be a little bit under or over the value that perfectly fills the OSD squares.

**Comment by unknowndomain** [comment]
This is perfect, might be helpful due to the small increments if you could make it so you can type or at least use up/down arrows, the qwirky UI makes it hard to get exact numbers as you have to use the mouse scroll whcih has acceleration on it.

**Comment by alin23** [comment]
You can actually use up and down arrows when the cursor is on the number you want to change.

**Comment by unknowndomain** [comment]
That works in the hover menu of the menu bar, but not in the configuration on the hotkeys.

**Comment by alin23** [comment]
Maybe try to quit and restart Lunar. There's no reason why this shouldn't work as long as Lunar is the frontmost app and you are hovering with the mouse over the number.

**Comment by alin23** [comment]
This should be fixed in Lunar 3.1. Let me know if there's anything that doesn't work as expected.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
