### ISSUE TITLE
Lunar Feature - Sidecar support

### ISSUE THREAD

**Issue by sfdye** [alin23/Lunar#80]
### Name of the feature

Support sidecar (iPad as physical display)

### What problem does this feature solve?

- Adjust brightness does not seen to work for iPad
- Unable to rename the name of display ("Celestrial")

### How should the feature work

- sidecar is supported
- Ability to rename display (maybe another FR)

### Visual description

NA

**Comment by alin23** [comment]
Unfortunately this is not possible. Sidecar uses airplay which has no support for changing brightness. Lunar uses DDC which is a wire protocol and could never work wirelessly. I can't even ignore the Sidecar displays in Lunar because they show up like any other display in the system, with no info about being a wireless display.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
