### ISSUE TITLE
[Bug] Sidecar force manual mode for main monitor

### ISSUE THREAD

**Issue by sfdye** [alin23/Lunar#83]
# Issue details
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    *write response here*

- Monitor model (LG UltraFine 5K, DELL P2715Q etc.):
    *write response here*

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
    *write response here*

- Using an USB Docking Station or Hub:
    *write yes or no here*

- Lunar mode used (check it in the top-right corner of the Lunar interface)
    **Location**

- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
    *optional response*

# Issue description:
*write a short description of what doesn't work as expected*

How to reproduce:
1. 1st monitor to use location mode
2. Airplay using Sidecar (iPad as 2nd monitor)
3. Stop Airplay
4. 1st monitor automatically becomes manual mode

**Comment by alin23** [comment]
It's not sidecar doing this. macOS resets the system display listing when you disconnect the iPad, and from Lunar's perspective, it looks like there's no monitor connected, and then a new monitor appears. 

But the events happen too fast sometimes and Lunar can't adjust fast enough. I also have the same setup, 1 monitor connected to Thunderbolt 3 and one Sidecar iPad, and this also happened to me but only once. I couldn't figure out what to do in the code to fix it, it's a system problem.

**Comment by sfdye** [comment]
Can't we persist the per monitor preference somewhere and reload from it once macOS resets?

**Comment by alin23** [comment]
We can't because the event we're talking about changes display IDs, and we use those IDs to know where to route the DDC messages. We always have to reset the whole display list when that event is triggered.

You didn't fill in the issue details though, that would have helped me understand the issue more.
What Mac device are you using?
Are you using a Macbook in clamshell mode?
Do you have _Clamshell mode detection_ enabled in Lunar? 
![image](https://user-images.githubusercontent.com/3819725/76681896-2bda9580-6600-11ea-873b-994cbcc4489f.png)

Maybe try disabling that option and check if the issue persists.
