### ISSUE TITLE
Lunar Diagnostics Report [9AF2D3FFB44515C4B356AF86A201204F560573E1A59413AA8E938C62A65B1849] [3.1.5]

### ISSUE THREAD

**Issue by nathantsmith** [alin23/Lunar#99]
# Issue details
- Was the diagnostics process able to change the brightness on your external monitor(s)?
    No
- Mac device where Lunar is installed (Macbook Pro 2019, iMac, Mac Mini, Hackintosh etc.):
    Macbook Air 2018

- Monitor connection to the Mac device (HDMI-to-USB-C, USB-C-to-USB-C, miniDisplayPort-to-DisplayPort etc.):
 USB -C dock HDMI
- Using an USB Docking Station or Hub:
Yes
- Lunar mode used (check it in the top-right corner of the Lunar interface)
Manual 
- (only if you know how to compile a C program) Does this utility work for you? https://github.com/kfix/ddcctl
   Able to read, not write, 
dell ultra sharp 27 

# Issue description:
*write a short description of what doesn't work as expected*
no visible changes on monitor.  willing to write a fix, but need to learn.

**Comment by alin23** [comment]
Hi @nathantsmith!
Thank you for the feedback!

If ddcctl can't write values to your monitor then Lunar won't be able to do that either. The problem is hardware related, either a bad cable or a bad connector or a non compliant dock. Try a direct connection between the MacBook and the monitor if possible or try using a different cable. 

There's nothing we could do in software to fix this as the problem is that the DDC write messages are not reaching your monitor properly.
